var searchData=
[
  ['udivoperator',['UDivOperator',['../d6/ddc/classllvm_1_1UDivOperator.html',1,'llvm']]],
  ['ufmax_5fpred_5fty',['ufmax_pred_ty',['../dc/dc3/structllvm_1_1PatternMatch_1_1ufmax__pred__ty.html',1,'llvm::PatternMatch']]],
  ['ufmin_5fpred_5fty',['ufmin_pred_ty',['../d8/d40/structllvm_1_1PatternMatch_1_1ufmin__pred__ty.html',1,'llvm::PatternMatch']]],
  ['uint128_5ft',['uint128_t',['../db/d9a/classuint128__t.html',1,'']]],
  ['uitofpinst',['UIToFPInst',['../d1/de5/classllvm_1_1UIToFPInst.html',1,'llvm']]],
  ['umax_5fpred_5fty',['umax_pred_ty',['../d4/d92/structllvm_1_1PatternMatch_1_1umax__pred__ty.html',1,'llvm::PatternMatch']]],
  ['umin_5fpred_5fty',['umin_pred_ty',['../d1/d91/structllvm_1_1PatternMatch_1_1umin__pred__ty.html',1,'llvm::PatternMatch']]],
  ['unaryconstantexpr',['UnaryConstantExpr',['../d6/d46/classllvm_1_1UnaryConstantExpr.html',1,'llvm']]],
  ['unaryexprast',['UnaryExprAST',['../d4/d7a/classUnaryExprAST.html',1,'']]],
  ['unaryinstruction',['UnaryInstruction',['../dd/d81/classllvm_1_1UnaryInstruction.html',1,'llvm']]],
  ['unarysdnode',['UnarySDNode',['../d6/dd1/classllvm_1_1UnarySDNode.html',1,'llvm']]],
  ['undefvalue',['UndefValue',['../d6/d8e/classllvm_1_1UndefValue.html',1,'llvm']]],
  ['unicodecharrange',['UnicodeCharRange',['../db/d79/structllvm_1_1sys_1_1UnicodeCharRange.html',1,'llvm::sys']]],
  ['unicodecharset',['UnicodeCharSet',['../d5/d37/classllvm_1_1sys_1_1UnicodeCharSet.html',1,'llvm::sys']]],
  ['unifyfunctionexitnodes',['UnifyFunctionExitNodes',['../d9/df2/structllvm_1_1UnifyFunctionExitNodes.html',1,'llvm']]],
  ['union_5fdoesnt_5fcontain_5ftype',['UNION_DOESNT_CONTAIN_TYPE',['../d0/d28/structllvm_1_1PointerUnion_1_1UNION__DOESNT__CONTAIN__TYPE.html',1,'llvm::PointerUnion']]],
  ['uniqueid',['UniqueID',['../d0/d1e/classllvm_1_1sys_1_1fs_1_1UniqueID.html',1,'llvm::sys::fs']]],
  ['uniquevector',['UniqueVector',['../d9/d2c/classllvm_1_1UniqueVector.html',1,'llvm']]],
  ['uniquevector_3c_20const_20comdat_20_2a_20_3e',['UniqueVector&lt; const Comdat * &gt;',['../d9/d2c/classllvm_1_1UniqueVector.html',1,'llvm']]],
  ['unittest',['UnitTest',['../d5/d21/classtesting_1_1UnitTest.html',1,'testing']]],
  ['unittestimpl',['UnitTestImpl',['../d0/de3/classtesting_1_1internal_1_1UnitTestImpl.html',1,'testing::internal']]],
  ['unittestoptions',['UnitTestOptions',['../d3/d9a/classtesting_1_1internal_1_1UnitTestOptions.html',1,'testing::internal']]],
  ['universalprinter',['UniversalPrinter',['../d6/d16/classtesting_1_1internal_1_1UniversalPrinter.html',1,'testing::internal']]],
  ['universalprinter_3c_20t_20_26_20_3e',['UniversalPrinter&lt; T &amp; &gt;',['../db/d6e/classtesting_1_1internal_1_1UniversalPrinter_3_01T_01_6_01_4.html',1,'testing::internal']]],
  ['universalprinter_3c_20t_5bn_5d_3e',['UniversalPrinter&lt; T[N]&gt;',['../da/db6/classtesting_1_1internal_1_1UniversalPrinter_3_01T[N]_4.html',1,'testing::internal']]],
  ['unopinit',['UnOpInit',['../d7/d55/classllvm_1_1UnOpInit.html',1,'llvm']]],
  ['unreachableinst',['UnreachableInst',['../d0/d0d/classllvm_1_1UnreachableInst.html',1,'llvm']]],
  ['unresolvederror',['UnresolvedError',['../dc/d7f/classlit_1_1LitTestCase_1_1UnresolvedError.html',1,'lit::LitTestCase']]],
  ['unrollingpreferences',['UnrollingPreferences',['../d6/dcd/structllvm_1_1TargetTransformInfo_1_1UnrollingPreferences.html',1,'llvm::TargetTransformInfo']]],
  ['unsetinit',['UnsetInit',['../d7/d62/classllvm_1_1UnsetInit.html',1,'llvm']]],
  ['unvalidatedmappingtraits',['unvalidatedMappingTraits',['../d9/def/structllvm_1_1yaml_1_1unvalidatedMappingTraits.html',1,'llvm::yaml']]],
  ['unwindcode',['UnwindCode',['../de/d35/unionllvm_1_1Win64EH_1_1UnwindCode.html',1,'llvm::Win64EH']]],
  ['unwindinfo',['UnwindInfo',['../d9/d31/structllvm_1_1Win64EH_1_1UnwindInfo.html',1,'llvm::Win64EH']]],
  ['unwindopcodeassembler',['UnwindOpcodeAssembler',['../d2/dab/classllvm_1_1UnwindOpcodeAssembler.html',1,'llvm']]],
  ['use',['Use',['../d0/d66/classllvm_1_1Use.html',1,'llvm']]],
  ['use_5fiterator',['use_iterator',['../de/d46/classllvm_1_1SDNode_1_1use__iterator.html',1,'llvm::SDNode']]],
  ['use_5fiterator_5fimpl',['use_iterator_impl',['../d6/dc4/classllvm_1_1Value_1_1use__iterator__impl.html',1,'llvm::Value']]],
  ['use_5fiterator_5fimpl_3c_20llvm_3a_3ause_20_3e',['use_iterator_impl&lt; llvm::Use &gt;',['../d6/dc4/classllvm_1_1Value_1_1use__iterator__impl.html',1,'llvm::Value']]],
  ['user',['User',['../d6/d1b/classllvm_1_1User.html',1,'llvm']]],
  ['user_5fiterator_5fimpl',['user_iterator_impl',['../d7/d1e/classllvm_1_1Value_1_1user__iterator__impl.html',1,'llvm::Value']]],
  ['usetovisit',['UseToVisit',['../d9/d8f/structllvm_1_1detail_1_1PtrUseVisitorBase_1_1UseToVisit.html',1,'llvm::detail::PtrUseVisitorBase']]],
  ['uuid_5fcommand',['uuid_command',['../d0/db3/structllvm_1_1MachO_1_1uuid__command.html',1,'llvm::MachO']]]
];
