var searchData=
[
  ['i',['i',['../d2/d96/classllvm_1_1types_1_1i.html',1,'llvm::types']]],
  ['icmapper',['ICMapper',['../d2/ddf/structllvm_1_1AArch64IC_1_1ICMapper.html',1,'llvm::AArch64IC']]],
  ['icmpinst',['ICmpInst',['../d5/dcb/classllvm_1_1ICmpInst.html',1,'llvm']]],
  ['ident_5fcommand',['ident_command',['../df/d16/structllvm_1_1MachO_1_1ident__command.html',1,'llvm::MachO']]],
  ['identifyingpassptr',['IdentifyingPassPtr',['../d1/d2e/classllvm_1_1IdentifyingPassPtr.html',1,'llvm']]],
  ['identity',['identity',['../de/de4/structllvm_1_1identity.html',1,'llvm']]],
  ['identity_3c_20unsigned_20_3e',['identity&lt; unsigned &gt;',['../de/de4/structllvm_1_1identity.html',1,'llvm']]],
  ['idf_5fext_5fiterator',['idf_ext_iterator',['../d2/d13/structllvm_1_1idf__ext__iterator.html',1,'llvm']]],
  ['idf_5fiterator',['idf_iterator',['../d3/d3f/structllvm_1_1idf__iterator.html',1,'llvm']]],
  ['idf_5fiterator_3c_20t_2c_20setty_2c_20true_20_3e',['idf_iterator&lt; T, SetTy, true &gt;',['../d3/d3f/structllvm_1_1idf__iterator.html',1,'llvm']]],
  ['idx2mbbcompare',['Idx2MBBCompare',['../d4/de4/structllvm_1_1Idx2MBBCompare.html',1,'llvm']]],
  ['ieee_5fdouble',['ieee_double',['../d6/d49/classllvm_1_1types_1_1ieee__double.html',1,'llvm::types']]],
  ['ieee_5ffloat',['ieee_float',['../d0/d2f/classllvm_1_1types_1_1ieee__float.html',1,'llvm::types']]],
  ['ifexprast',['IfExprAST',['../d5/d7a/classIfExprAST.html',1,'']]],
  ['iitdescriptor',['IITDescriptor',['../d9/d24/structllvm_1_1Intrinsic_1_1IITDescriptor.html',1,'llvm::Intrinsic']]],
  ['ilist',['ilist',['../d6/d05/structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20indexlistentry_20_3e',['ilist&lt; IndexListEntry &gt;',['../d6/d05/structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20llvm_3a_3aaliasset_20_3e',['ilist&lt; llvm::AliasSet &gt;',['../d6/d05/structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20llvm_3a_3aivstrideuse_20_3e',['ilist&lt; llvm::IVStrideUse &gt;',['../d6/d05/structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20llvm_3a_3asdnode_20_3e',['ilist&lt; llvm::SDNode &gt;',['../d6/d05/structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20machinebasicblock_20_3e',['ilist&lt; MachineBasicBlock &gt;',['../d6/d05/structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20machineinstr_20_3e',['ilist&lt; MachineInstr &gt;',['../d6/d05/structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20namedmdnode_20_3e',['ilist&lt; NamedMDNode &gt;',['../d6/d05/structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['ilist&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../d6/d05/structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20token_20_3e',['ilist&lt; Token &gt;',['../d6/d05/structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits',['ilist_default_traits',['../d7/d9a/structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20indexlistentry_20_3e',['ilist_default_traits&lt; IndexListEntry &gt;',['../d7/d9a/structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20ivstrideuse_20_3e',['ilist_default_traits&lt; IVStrideUse &gt;',['../d7/d9a/structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20machinebasicblock_20_3e',['ilist_default_traits&lt; MachineBasicBlock &gt;',['../d7/d9a/structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20machineinstr_20_3e',['ilist_default_traits&lt; MachineInstr &gt;',['../d7/d9a/structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20namedmdnode_20_3e',['ilist_default_traits&lt; NamedMDNode &gt;',['../d7/d9a/structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20recyclerstruct_20_3e',['ilist_default_traits&lt; RecyclerStruct &gt;',['../d7/d9a/structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20sdnode_20_3e',['ilist_default_traits&lt; SDNode &gt;',['../d7/d9a/structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['ilist_default_traits&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../d7/d9a/structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20valuesubclass_20_3e',['ilist_default_traits&lt; ValueSubClass &gt;',['../d7/d9a/structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode',['ilist_half_node',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20aliasset_20_3e',['ilist_half_node&lt; AliasSet &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20argument_20_3e',['ilist_half_node&lt; Argument &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20basicblock_20_3e',['ilist_half_node&lt; BasicBlock &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20function_20_3e',['ilist_half_node&lt; Function &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20globalalias_20_3e',['ilist_half_node&lt; GlobalAlias &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20globalvariable_20_3e',['ilist_half_node&lt; GlobalVariable &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20indexlistentry_20_3e',['ilist_half_node&lt; IndexListEntry &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20instruction_20_3e',['ilist_half_node&lt; Instruction &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20ivstrideuse_20_3e',['ilist_half_node&lt; IVStrideUse &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3aargument_20_3e',['ilist_half_node&lt; llvm::Argument &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3abasicblock_20_3e',['ilist_half_node&lt; llvm::BasicBlock &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3afunction_20_3e',['ilist_half_node&lt; llvm::Function &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3aglobalalias_20_3e',['ilist_half_node&lt; llvm::GlobalAlias &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3aglobalvariable_20_3e',['ilist_half_node&lt; llvm::GlobalVariable &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3aindexlistentry_20_3e',['ilist_half_node&lt; llvm::IndexListEntry &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3ainstruction_20_3e',['ilist_half_node&lt; llvm::Instruction &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3aivstrideuse_20_3e',['ilist_half_node&lt; llvm::IVStrideUse &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3amachinebasicblock_20_3e',['ilist_half_node&lt; llvm::MachineBasicBlock &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3amachineinstr_20_3e',['ilist_half_node&lt; llvm::MachineInstr &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3anamedmdnode_20_3e',['ilist_half_node&lt; llvm::NamedMDNode &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3asdnode_20_3e',['ilist_half_node&lt; llvm::SDNode &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3asparsebitvectorelement_20_3e',['ilist_half_node&lt; llvm::SparseBitVectorElement &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20machinebasicblock_20_3e',['ilist_half_node&lt; MachineBasicBlock &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20machineinstr_20_3e',['ilist_half_node&lt; MachineInstr &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20mcfragment_20_3e',['ilist_half_node&lt; MCFragment &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20mcsectiondata_20_3e',['ilist_half_node&lt; MCSectionData &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20mcsymboldata_20_3e',['ilist_half_node&lt; MCSymbolData &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20namedmdnode_20_3e',['ilist_half_node&lt; NamedMDNode &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20node_20_3e',['ilist_half_node&lt; Node &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20sdnode_20_3e',['ilist_half_node&lt; SDNode &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['ilist_half_node&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20state_20_3e',['ilist_half_node&lt; State &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20token_20_3e',['ilist_half_node&lt; Token &gt;',['../d3/d42/classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fiterator',['ilist_iterator',['../d0/dc1/classllvm_1_1ilist__iterator.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits',['ilist_nextprev_traits',['../d5/d1d/structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20indexlistentry_20_3e',['ilist_nextprev_traits&lt; IndexListEntry &gt;',['../d5/d1d/structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20ivstrideuse_20_3e',['ilist_nextprev_traits&lt; IVStrideUse &gt;',['../d5/d1d/structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20machinebasicblock_20_3e',['ilist_nextprev_traits&lt; MachineBasicBlock &gt;',['../d5/d1d/structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20machineinstr_20_3e',['ilist_nextprev_traits&lt; MachineInstr &gt;',['../d5/d1d/structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20namedmdnode_20_3e',['ilist_nextprev_traits&lt; NamedMDNode &gt;',['../d5/d1d/structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20recyclerstruct_20_3e',['ilist_nextprev_traits&lt; RecyclerStruct &gt;',['../d5/d1d/structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20sdnode_20_3e',['ilist_nextprev_traits&lt; SDNode &gt;',['../d5/d1d/structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['ilist_nextprev_traits&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../d5/d1d/structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20valuesubclass_20_3e',['ilist_nextprev_traits&lt; ValueSubClass &gt;',['../d5/d1d/structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnode',['ilist_node',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20aliasset_20_3e',['ilist_node&lt; AliasSet &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20argument_20_3e',['ilist_node&lt; Argument &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20basicblock_20_3e',['ilist_node&lt; BasicBlock &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20function_20_3e',['ilist_node&lt; Function &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20globalalias_20_3e',['ilist_node&lt; GlobalAlias &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20globalvariable_20_3e',['ilist_node&lt; GlobalVariable &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20indexlistentry_20_3e',['ilist_node&lt; IndexListEntry &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20instruction_20_3e',['ilist_node&lt; Instruction &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20ivstrideuse_20_3e',['ilist_node&lt; IVStrideUse &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20llvm_3a_3afunction_20_3e',['ilist_node&lt; llvm::Function &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20llvm_3a_3aglobalalias_20_3e',['ilist_node&lt; llvm::GlobalAlias &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20llvm_3a_3aglobalvariable_20_3e',['ilist_node&lt; llvm::GlobalVariable &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20llvm_3a_3aivstrideuse_20_3e',['ilist_node&lt; llvm::IVStrideUse &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20llvm_3a_3anamedmdnode_20_3e',['ilist_node&lt; llvm::NamedMDNode &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20machinebasicblock_20_3e',['ilist_node&lt; MachineBasicBlock &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20machineinstr_20_3e',['ilist_node&lt; MachineInstr &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20mcfragment_20_3e',['ilist_node&lt; MCFragment &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20mcsectiondata_20_3e',['ilist_node&lt; MCSectionData &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20mcsymboldata_20_3e',['ilist_node&lt; MCSymbolData &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20namedmdnode_20_3e',['ilist_node&lt; NamedMDNode &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20node_20_3e',['ilist_node&lt; Node &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20sdnode_20_3e',['ilist_node&lt; SDNode &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['ilist_node&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20state_20_3e',['ilist_node&lt; State &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20token_20_3e',['ilist_node&lt; Token &gt;',['../d3/db5/classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits',['ilist_node_traits',['../d9/d93/structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20indexlistentry_20_3e',['ilist_node_traits&lt; IndexListEntry &gt;',['../d9/d93/structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20ivstrideuse_20_3e',['ilist_node_traits&lt; IVStrideUse &gt;',['../d9/d93/structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20machinebasicblock_20_3e',['ilist_node_traits&lt; MachineBasicBlock &gt;',['../d9/d93/structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20machineinstr_20_3e',['ilist_node_traits&lt; MachineInstr &gt;',['../d9/d93/structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20namedmdnode_20_3e',['ilist_node_traits&lt; NamedMDNode &gt;',['../d9/d93/structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20recyclerstruct_20_3e',['ilist_node_traits&lt; RecyclerStruct &gt;',['../d9/d93/structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20sdnode_20_3e',['ilist_node_traits&lt; SDNode &gt;',['../d9/d93/structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['ilist_node_traits&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../d9/d93/structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20token_20_3e',['ilist_node_traits&lt; Token &gt;',['../d4/d83/structllvm_1_1ilist__node__traits_3_01Token_01_4.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20valuesubclass_20_3e',['ilist_node_traits&lt; ValueSubClass &gt;',['../d9/d93/structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits',['ilist_sentinel_traits',['../d1/d6e/structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20indexlistentry_20_3e',['ilist_sentinel_traits&lt; IndexListEntry &gt;',['../d1/d6e/structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20ivstrideuse_20_3e',['ilist_sentinel_traits&lt; IVStrideUse &gt;',['../d1/d6e/structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20machinebasicblock_20_3e',['ilist_sentinel_traits&lt; MachineBasicBlock &gt;',['../d1/d6e/structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20machineinstr_20_3e',['ilist_sentinel_traits&lt; MachineInstr &gt;',['../d1/d6e/structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20namedmdnode_20_3e',['ilist_sentinel_traits&lt; NamedMDNode &gt;',['../d1/d6e/structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20recyclerstruct_20_3e',['ilist_sentinel_traits&lt; RecyclerStruct &gt;',['../d1/d6e/structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20sdnode_20_3e',['ilist_sentinel_traits&lt; SDNode &gt;',['../d1/d6e/structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['ilist_sentinel_traits&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../d1/d6e/structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20token_20_3e',['ilist_sentinel_traits&lt; Token &gt;',['../d2/de3/structllvm_1_1ilist__sentinel__traits_3_01Token_01_4.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20valuesubclass_20_3e',['ilist_sentinel_traits&lt; ValueSubClass &gt;',['../d1/d6e/structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5ftraits',['ilist_traits',['../d5/dbe/structllvm_1_1ilist__traits.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20argument_20_3e',['ilist_traits&lt; Argument &gt;',['../d0/d17/structllvm_1_1ilist__traits_3_01Argument_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20basicblock_20_3e',['ilist_traits&lt; BasicBlock &gt;',['../da/daa/structllvm_1_1ilist__traits_3_01BasicBlock_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20const_20ty_20_3e',['ilist_traits&lt; const Ty &gt;',['../d5/d0e/structllvm_1_1ilist__traits_3_01const_01Ty_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20function_20_3e',['ilist_traits&lt; Function &gt;',['../d8/d8a/structllvm_1_1ilist__traits_3_01Function_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20globalalias_20_3e',['ilist_traits&lt; GlobalAlias &gt;',['../de/d99/structllvm_1_1ilist__traits_3_01GlobalAlias_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20globalvariable_20_3e',['ilist_traits&lt; GlobalVariable &gt;',['../df/d4c/structllvm_1_1ilist__traits_3_01GlobalVariable_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20indexlistentry_20_3e',['ilist_traits&lt; IndexListEntry &gt;',['../d6/ddd/structllvm_1_1ilist__traits_3_01IndexListEntry_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20instruction_20_3e',['ilist_traits&lt; Instruction &gt;',['../d0/d2c/structllvm_1_1ilist__traits_3_01Instruction_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20ivstrideuse_20_3e',['ilist_traits&lt; IVStrideUse &gt;',['../d4/dae/structllvm_1_1ilist__traits_3_01IVStrideUse_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20machinebasicblock_20_3e',['ilist_traits&lt; MachineBasicBlock &gt;',['../d2/ddf/structllvm_1_1ilist__traits_3_01MachineBasicBlock_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20machineinstr_20_3e',['ilist_traits&lt; MachineInstr &gt;',['../d8/d2d/structllvm_1_1ilist__traits_3_01MachineInstr_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20namedmdnode_20_3e',['ilist_traits&lt; NamedMDNode &gt;',['../dd/d83/structllvm_1_1ilist__traits_3_01NamedMDNode_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20recyclerstruct_20_3e',['ilist_traits&lt; RecyclerStruct &gt;',['../de/d19/structllvm_1_1ilist__traits_3_01RecyclerStruct_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20sdnode_20_3e',['ilist_traits&lt; SDNode &gt;',['../d1/db0/structllvm_1_1ilist__traits_3_01SDNode_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['ilist_traits&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../db/dd7/structllvm_1_1ilist__traits_3_01SparseBitVectorElement_3_01ElementSize_01_4_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20ty_20_3e',['ilist_traits&lt; Ty &gt;',['../d5/dbe/structllvm_1_1ilist__traits.html',1,'llvm']]],
  ['ilpvalue',['ILPValue',['../d4/dd3/structllvm_1_1ILPValue.html',1,'llvm']]],
  ['immop',['ImmOp',['../d6/d73/structllvm_1_1X86Operand_1_1ImmOp.html',1,'llvm::X86Operand']]],
  ['immutablecallsite',['ImmutableCallSite',['../d7/dbe/classllvm_1_1ImmutableCallSite.html',1,'llvm']]],
  ['immutablelist',['ImmutableList',['../d3/d25/classllvm_1_1ImmutableList.html',1,'llvm']]],
  ['immutablelistfactory',['ImmutableListFactory',['../de/dd7/classllvm_1_1ImmutableListFactory.html',1,'llvm']]],
  ['immutablelistimpl',['ImmutableListImpl',['../d9/ddf/classllvm_1_1ImmutableListImpl.html',1,'llvm']]],
  ['immutablemap',['ImmutableMap',['../d1/d7c/classllvm_1_1ImmutableMap.html',1,'llvm']]],
  ['immutablemapref',['ImmutableMapRef',['../d0/d28/classllvm_1_1ImmutableMapRef.html',1,'llvm']]],
  ['immutablepass',['ImmutablePass',['../d6/dcd/classllvm_1_1ImmutablePass.html',1,'llvm']]],
  ['immutableset',['ImmutableSet',['../d2/d88/classllvm_1_1ImmutableSet.html',1,'llvm']]],
  ['immutablesetref',['ImmutableSetRef',['../d7/dd4/classllvm_1_1ImmutableSetRef.html',1,'llvm']]],
  ['implicitlyconvertible',['ImplicitlyConvertible',['../d1/d75/classtesting_1_1internal_1_1ImplicitlyConvertible.html',1,'testing::internal']]],
  ['import_5fdirectory_5ftable_5fentry',['import_directory_table_entry',['../d8/d16/structllvm_1_1object_1_1import__directory__table__entry.html',1,'llvm::object']]],
  ['import_5flookup_5ftable_5fentry32',['import_lookup_table_entry32',['../de/d09/structllvm_1_1object_1_1import__lookup__table__entry32.html',1,'llvm::object']]],
  ['importdirectoryentryref',['ImportDirectoryEntryRef',['../dc/da6/classllvm_1_1object_1_1ImportDirectoryEntryRef.html',1,'llvm::object']]],
  ['importdirectorytableentry',['ImportDirectoryTableEntry',['../d8/db6/structllvm_1_1COFF_1_1ImportDirectoryTableEntry.html',1,'llvm::COFF']]],
  ['importheader',['ImportHeader',['../de/dc6/structllvm_1_1COFF_1_1ImportHeader.html',1,'llvm::COFF']]],
  ['importlookuptableentry32',['ImportLookupTableEntry32',['../de/d1b/structllvm_1_1COFF_1_1ImportLookupTableEntry32.html',1,'llvm::COFF']]],
  ['imutavlfactory',['ImutAVLFactory',['../d0/d39/classllvm_1_1ImutAVLFactory.html',1,'llvm']]],
  ['imutavltree',['ImutAVLTree',['../df/d30/classllvm_1_1ImutAVLTree.html',1,'llvm']]],
  ['imutavltreegenericiterator',['ImutAVLTreeGenericIterator',['../dc/d08/classllvm_1_1ImutAVLTreeGenericIterator.html',1,'llvm']]],
  ['imutavltreeinorderiterator',['ImutAVLTreeInOrderIterator',['../db/d46/classllvm_1_1ImutAVLTreeInOrderIterator.html',1,'llvm']]],
  ['imutcontainerinfo',['ImutContainerInfo',['../dd/d8a/structllvm_1_1ImutContainerInfo.html',1,'llvm']]],
  ['imutcontainerinfo_3c_20t_20_2a_20_3e',['ImutContainerInfo&lt; T * &gt;',['../d9/dbb/structllvm_1_1ImutContainerInfo_3_01T_01_5_01_4.html',1,'llvm']]],
  ['imutintervalavlfactory',['ImutIntervalAVLFactory',['../da/dc4/classllvm_1_1ImutIntervalAVLFactory.html',1,'llvm']]],
  ['imutkeyvalueinfo',['ImutKeyValueInfo',['../d3/d38/structllvm_1_1ImutKeyValueInfo.html',1,'llvm']]],
  ['imutprofileinfo',['ImutProfileInfo',['../d4/da6/structllvm_1_1ImutProfileInfo.html',1,'llvm']]],
  ['imutprofileinfo_3c_20bool_20_3e',['ImutProfileInfo&lt; bool &gt;',['../d7/d52/structllvm_1_1ImutProfileInfo_3_01bool_01_4.html',1,'llvm']]],
  ['imutprofileinfo_3c_20t_20_2a_20_3e',['ImutProfileInfo&lt; T * &gt;',['../df/d6e/structllvm_1_1ImutProfileInfo_3_01T_01_5_01_4.html',1,'llvm']]],
  ['imutprofileinteger',['ImutProfileInteger',['../d7/d9c/structllvm_1_1ImutProfileInteger.html',1,'llvm']]],
  ['includefile',['IncludeFile',['../db/d28/structllvm_1_1IncludeFile.html',1,'llvm']]],
  ['indent',['indent',['../d2/dd2/structindent.html',1,'']]],
  ['indexedinstrprofreader',['IndexedInstrProfReader',['../d9/da3/classllvm_1_1IndexedInstrProfReader.html',1,'llvm']]],
  ['indexedmap',['IndexedMap',['../d6/d06/classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20int_2c_20llvm_3a_3avirtreg2indexfunctor_20_3e',['IndexedMap&lt; int, llvm::VirtReg2IndexFunctor &gt;',['../d6/d06/classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20liveoutpair_2c_20mbb2numberfunctor_20_3e',['IndexedMap&lt; LiveOutPair, MBB2NumberFunctor &gt;',['../d6/d06/classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20llvm_3a_3afunctionloweringinfo_3a_3aliveoutinfo_2c_20llvm_3a_3avirtreg2indexfunctor_20_3e',['IndexedMap&lt; llvm::FunctionLoweringInfo::LiveOutInfo, llvm::VirtReg2IndexFunctor &gt;',['../d6/d06/classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20llvm_3a_3aliveinterval_20_2a_2c_20llvm_3a_3avirtreg2indexfunctor_20_3e',['IndexedMap&lt; llvm::LiveInterval *, llvm::VirtReg2IndexFunctor &gt;',['../d6/d06/classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20llvm_3a_3alivevariables_3a_3avarinfo_2c_20llvm_3a_3avirtreg2indexfunctor_20_3e',['IndexedMap&lt; llvm::LiveVariables::VarInfo, llvm::VirtReg2IndexFunctor &gt;',['../d6/d06/classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20std_3a_3apair_3c_20const_20llvm_3a_3atargetregisterclass_20_2a_2c_20llvm_3a_3amachineoperand_20_2a_20_3e_2c_20llvm_3a_3avirtreg2indexfunctor_20_3e',['IndexedMap&lt; std::pair&lt; const llvm::TargetRegisterClass *, llvm::MachineOperand * &gt;, llvm::VirtReg2IndexFunctor &gt;',['../d6/d06/classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20std_3a_3apair_3c_20unsigned_2c_20unsigned_20_3e_2c_20llvm_3a_3avirtreg2indexfunctor_20_3e',['IndexedMap&lt; std::pair&lt; unsigned, unsigned &gt;, llvm::VirtReg2IndexFunctor &gt;',['../d6/d06/classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20unsigned_20_3e',['IndexedMap&lt; unsigned &gt;',['../d6/d06/classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20unsigned_2c_20llvm_3a_3avirtreg2indexfunctor_20_3e',['IndexedMap&lt; unsigned, llvm::VirtReg2IndexFunctor &gt;',['../d6/d06/classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexlistentry',['IndexListEntry',['../de/ddd/classllvm_1_1IndexListEntry.html',1,'llvm']]],
  ['indirectbrinst',['IndirectBrInst',['../d6/d82/classllvm_1_1IndirectBrInst.html',1,'llvm']]],
  ['indirectsymboldata',['IndirectSymbolData',['../d4/def/structllvm_1_1IndirectSymbolData.html',1,'llvm']]],
  ['info',['Info',['../dd/dc6/structllvm_1_1opt_1_1OptTable_1_1Info.html',1,'llvm::opt::OptTable']]],
  ['inforec',['InfoRec',['../d3/d89/structllvm_1_1DominatorTreeBase_1_1InfoRec.html',1,'llvm::DominatorTreeBase']]],
  ['iniformatparser',['IniFormatParser',['../df/d41/classllvmbuild_1_1componentinfo_1_1IniFormatParser.html',1,'llvmbuild::componentinfo']]],
  ['init',['Init',['../df/d88/classllvm_1_1Init.html',1,'llvm']]],
  ['initializer',['initializer',['../d9/d17/structllvm_1_1cl_1_1initializer.html',1,'llvm::cl']]],
  ['inlineasm',['InlineAsm',['../d0/d53/classllvm_1_1InlineAsm.html',1,'llvm']]],
  ['inlineasmidentifierinfo',['InlineAsmIdentifierInfo',['../d5/d29/classllvm_1_1InlineAsmIdentifierInfo.html',1,'llvm']]],
  ['inlineasmkeytype',['InlineAsmKeyType',['../dc/d5a/structllvm_1_1InlineAsmKeyType.html',1,'llvm']]],
  ['inlinecost',['InlineCost',['../dc/ded/classllvm_1_1InlineCost.html',1,'llvm']]],
  ['inlinecostanalysis',['InlineCostAnalysis',['../dc/d39/classllvm_1_1InlineCostAnalysis.html',1,'llvm']]],
  ['inlinefunctioninfo',['InlineFunctionInfo',['../d0/d76/classllvm_1_1InlineFunctionInfo.html',1,'llvm']]],
  ['inliner',['Inliner',['../d8/d62/structllvm_1_1Inliner.html',1,'llvm']]],
  ['input',['Input',['../dc/d4a/classllvm_1_1yaml_1_1Input.html',1,'llvm::yaml']]],
  ['inputarg',['InputArg',['../db/d36/structllvm_1_1ISD_1_1InputArg.html',1,'llvm::ISD']]],
  ['inputarglist',['InputArgList',['../db/d66/classllvm_1_1opt_1_1InputArgList.html',1,'llvm::opt']]],
  ['insertelementconstantexpr',['InsertElementConstantExpr',['../d2/d66/classllvm_1_1InsertElementConstantExpr.html',1,'llvm']]],
  ['insertelementinst',['InsertElementInst',['../d4/d50/classllvm_1_1InsertElementInst.html',1,'llvm']]],
  ['insertpoint',['InsertPoint',['../d7/dfc/classllvm_1_1IRBuilderBase_1_1InsertPoint.html',1,'llvm::IRBuilderBase']]],
  ['insertpointguard',['InsertPointGuard',['../d8/d50/classllvm_1_1IRBuilderBase_1_1InsertPointGuard.html',1,'llvm::IRBuilderBase']]],
  ['insertvalueconstantexpr',['InsertValueConstantExpr',['../d5/dee/classllvm_1_1InsertValueConstantExpr.html',1,'llvm']]],
  ['insertvalueinst',['InsertValueInst',['../db/d73/classllvm_1_1InsertValueInst.html',1,'llvm']]],
  ['inst',['Inst',['../d0/d1c/structllvm_1_1MCModuleYAML_1_1Inst.html',1,'llvm::MCModuleYAML']]],
  ['inst',['Inst',['../de/d1f/structllvm_1_1MipsAnalyzeImmediate_1_1Inst.html',1,'llvm::MipsAnalyzeImmediate']]],
  ['instanalyzer',['InstAnalyzer',['../dc/d10/classInstAnalyzer.html',1,'']]],
  ['instcombineirinserter',['InstCombineIRInserter',['../d4/def/classllvm_1_1InstCombineIRInserter.html',1,'llvm']]],
  ['instcombiner',['InstCombiner',['../d5/dc0/classllvm_1_1InstCombiner.html',1,'llvm']]],
  ['instcombineworklist',['InstCombineWorklist',['../d9/df2/classllvm_1_1InstCombineWorklist.html',1,'llvm']]],
  ['institerator',['InstIterator',['../db/d30/classllvm_1_1InstIterator.html',1,'llvm']]],
  ['institerator_3c_20const_20iplist_3c_20basicblock_20_3e_2c_20function_3a_3aconst_5fiterator_2c_20basicblock_3a_3aconst_5fiterator_2c_20const_20instruction_20_3e',['InstIterator&lt; const iplist&lt; BasicBlock &gt;, Function::const_iterator, BasicBlock::const_iterator, const Instruction &gt;',['../db/d30/classllvm_1_1InstIterator.html',1,'llvm']]],
  ['instrcycles',['InstrCycles',['../da/dae/structllvm_1_1MachineTraceMetrics_1_1InstrCycles.html',1,'llvm::MachineTraceMetrics']]],
  ['instremitter',['InstrEmitter',['../dd/d19/classllvm_1_1InstrEmitter.html',1,'llvm']]],
  ['instrinfoty',['InstrInfoTy',['../d1/d7a/structllvm_1_1WinCodeViewLineTables_1_1InstrInfoTy.html',1,'llvm::WinCodeViewLineTables']]],
  ['instritinerary',['InstrItinerary',['../d9/dc7/structllvm_1_1InstrItinerary.html',1,'llvm']]],
  ['instritinerarydata',['InstrItineraryData',['../d3/dd5/classllvm_1_1InstrItineraryData.html',1,'llvm']]],
  ['instrprofiterator',['InstrProfIterator',['../de/d33/classllvm_1_1InstrProfIterator.html',1,'llvm']]],
  ['instrproflookuptrait',['InstrProfLookupTrait',['../d2/df5/classllvm_1_1InstrProfLookupTrait.html',1,'llvm']]],
  ['instrprofreader',['InstrProfReader',['../dd/d27/classllvm_1_1InstrProfReader.html',1,'llvm']]],
  ['instrprofrecord',['InstrProfRecord',['../d7/da6/structllvm_1_1InstrProfRecord.html',1,'llvm']]],
  ['instrprofwriter',['InstrProfWriter',['../dc/d53/classllvm_1_1InstrProfWriter.html',1,'llvm']]],
  ['instrstage',['InstrStage',['../d5/d53/structllvm_1_1InstrStage.html',1,'llvm']]],
  ['instruction',['Instruction',['../d5/dd1/structllvm_1_1Win64EH_1_1Instruction.html',1,'llvm::Win64EH']]],
  ['instruction',['Instruction',['../d2/d88/classllvm_1_1Instruction.html',1,'llvm']]],
  ['instruction',['Instruction',['../de/d23/structllvm_1_1FrameEntry_1_1Instruction.html',1,'llvm::FrameEntry']]],
  ['instruction',['Instruction',['../d4/df3/classllvm_1_1core_1_1Instruction.html',1,'llvm::core']]],
  ['instruction',['Instruction',['../db/d4e/structllvm_1_1WinEH_1_1Instruction.html',1,'llvm::WinEH']]],
  ['instructionnode',['InstructionNode',['../d6/d2d/classlegup_1_1InstructionNode.html',1,'legup']]],
  ['instructionspecifier',['InstructionSpecifier',['../d6/dc4/structllvm_1_1X86Disassembler_1_1InstructionSpecifier.html',1,'llvm::X86Disassembler']]],
  ['instructionspecifier',['InstructionSpecifier',['../dc/d4c/structInstructionSpecifier.html',1,'']]],
  ['instvisitor',['InstVisitor',['../db/d38/classllvm_1_1InstVisitor.html',1,'llvm']]],
  ['instvisitor_3c_20derivedt_20_3e',['InstVisitor&lt; DerivedT &gt;',['../db/d38/classllvm_1_1InstVisitor.html',1,'llvm']]],
  ['instvisitor_3c_20generatertl_20_3e',['InstVisitor&lt; GenerateRTL &gt;',['../db/d38/classllvm_1_1InstVisitor.html',1,'llvm']]],
  ['instvisitor_3c_20instcombiner_2c_20instruction_20_2a_20_3e',['InstVisitor&lt; InstCombiner, Instruction * &gt;',['../db/d38/classllvm_1_1InstVisitor.html',1,'llvm']]],
  ['instvisitor_3c_20interpreter_20_3e',['InstVisitor&lt; Interpreter &gt;',['../db/d38/classllvm_1_1InstVisitor.html',1,'llvm']]],
  ['instvisitor_3c_20leguppass_20_3e',['InstVisitor&lt; LegupPass &gt;',['../db/d38/classllvm_1_1InstVisitor.html',1,'llvm']]],
  ['instvisitor_3c_20objectsizeoffsetevaluator_2c_20sizeoffsetevaltype_20_3e',['InstVisitor&lt; ObjectSizeOffsetEvaluator, SizeOffsetEvalType &gt;',['../db/d38/classllvm_1_1InstVisitor.html',1,'llvm']]],
  ['instvisitor_3c_20objectsizeoffsetvisitor_2c_20sizeoffsettype_20_3e',['InstVisitor&lt; ObjectSizeOffsetVisitor, SizeOffsetType &gt;',['../db/d38/classllvm_1_1InstVisitor.html',1,'llvm']]],
  ['instvisitor_3c_20slicebuilder_20_3e',['InstVisitor&lt; SliceBuilder &gt;',['../db/d38/classllvm_1_1InstVisitor.html',1,'llvm']]],
  ['intattributeimpl',['IntAttributeImpl',['../d2/d29/classllvm_1_1IntAttributeImpl.html',1,'llvm']]],
  ['integertype',['IntegerType',['../dd/d56/classllvm_1_1IntegerType.html',1,'llvm']]],
  ['inteljiteventlistenertest',['IntelJITEventListenerTest',['../df/d42/classIntelJITEventListenerTest.html',1,'']]],
  ['inteljiteventswrapper',['IntelJITEventsWrapper',['../da/d4f/classllvm_1_1IntelJITEventsWrapper.html',1,'llvm']]],
  ['inteqclasses',['IntEqClasses',['../d6/df7/classllvm_1_1IntEqClasses.html',1,'llvm']]],
  ['interceptrefcounted',['InterceptRefCounted',['../d5/d19/structllvm_1_1InterceptRefCounted.html',1,'llvm']]],
  ['interferencecache',['InterferenceCache',['../d0/d09/classllvm_1_1InterferenceCache.html',1,'llvm']]],
  ['internaldata',['InternalData',['../d9/d19/structLineEditor_1_1InternalData.html',1,'llvm::LineEditor']]],
  ['internalinstruction',['InternalInstruction',['../d1/d98/structllvm_1_1X86Disassembler_1_1InternalInstruction.html',1,'llvm::X86Disassembler']]],
  ['internalshellerror',['InternalShellError',['../d8/df2/classlit_1_1TestRunner_1_1InternalShellError.html',1,'lit::TestRunner']]],
  ['interpreter',['Interpreter',['../d3/de3/classllvm_1_1Interpreter.html',1,'llvm']]],
  ['interval',['Interval',['../de/d26/classllvm_1_1Interval.html',1,'llvm']]],
  ['intervaliterator',['IntervalIterator',['../da/d03/classllvm_1_1IntervalIterator.html',1,'llvm']]],
  ['intervalmap',['IntervalMap',['../d3/d39/classllvm_1_1IntervalMap.html',1,'llvm']]],
  ['intervalmap_3c_20slotindex_2c_20liveinterval_20_2a_20_3e',['IntervalMap&lt; SlotIndex, LiveInterval * &gt;',['../d3/d39/classllvm_1_1IntervalMap.html',1,'llvm']]],
  ['intervalmap_3c_20slotindex_2c_20unsigned_20_3e',['IntervalMap&lt; SlotIndex, unsigned &gt;',['../d3/d39/classllvm_1_1IntervalMap.html',1,'llvm']]],
  ['intervalmaphalfopeninfo',['IntervalMapHalfOpenInfo',['../dd/d40/structllvm_1_1IntervalMapHalfOpenInfo.html',1,'llvm']]],
  ['intervalmaphalfopeninfo_3c_20slotindex_20_3e',['IntervalMapHalfOpenInfo&lt; SlotIndex &gt;',['../dd/d40/structllvm_1_1IntervalMapHalfOpenInfo.html',1,'llvm']]],
  ['intervalmapinfo',['IntervalMapInfo',['../d3/d63/structllvm_1_1IntervalMapInfo.html',1,'llvm']]],
  ['intervalmapinfo_3c_20slotindex_20_3e',['IntervalMapInfo&lt; SlotIndex &gt;',['../dc/d39/structllvm_1_1IntervalMapInfo_3_01SlotIndex_01_4.html',1,'llvm']]],
  ['intervalmapoverlaps',['IntervalMapOverlaps',['../d8/d5b/classllvm_1_1IntervalMapOverlaps.html',1,'llvm']]],
  ['intervalpartition',['IntervalPartition',['../d3/d77/classllvm_1_1IntervalPartition.html',1,'llvm']]],
  ['intervalpressure',['IntervalPressure',['../dc/dac/structllvm_1_1IntervalPressure.html',1,'llvm']]],
  ['intervalsorter',['IntervalSorter',['../d4/d69/structfalse_1_1IntervalSorter.html',1,'false']]],
  ['intinit',['IntInit',['../d7/d52/classllvm_1_1IntInit.html',1,'llvm']]],
  ['intmetricvalue',['IntMetricValue',['../da/db5/classlit_1_1Test_1_1IntMetricValue.html',1,'lit::Test']]],
  ['intpair',['IntPair',['../de/d72/structllvm_1_1GenericValue_1_1IntPair.html',1,'llvm::GenericValue']]],
  ['intpredicate',['IntPredicate',['../d8/d5e/classllvm_1_1core_1_1IntPredicate.html',1,'llvm::core']]],
  ['intrecty',['IntRecTy',['../d4/d04/classllvm_1_1IntRecTy.html',1,'llvm']]],
  ['intrinsicdata',['IntrinsicData',['../d6/d91/structIntrinsicData.html',1,'']]],
  ['intrinsicid_5fmatch',['IntrinsicID_match',['../dc/d25/structllvm_1_1PatternMatch_1_1IntrinsicID__match.html',1,'llvm::PatternMatch']]],
  ['intrinsicinfo',['IntrinsicInfo',['../d6/d46/structllvm_1_1TargetLoweringBase_1_1IntrinsicInfo.html',1,'llvm::TargetLoweringBase']]],
  ['intrinsicinst',['IntrinsicInst',['../df/da2/classllvm_1_1IntrinsicInst.html',1,'llvm']]],
  ['intrinsiclowering',['IntrinsicLowering',['../d5/de2/classllvm_1_1IntrinsicLowering.html',1,'llvm']]],
  ['intrinsicsignature',['IntrinsicSignature',['../dc/dec/structllvm_1_1CodeGenIntrinsic_1_1IntrinsicSignature.html',1,'llvm::CodeGenIntrinsic']]],
  ['intrusiverefcntptr',['IntrusiveRefCntPtr',['../d5/d48/classllvm_1_1IntrusiveRefCntPtr.html',1,'llvm']]],
  ['intrusiverefcntptr_3c_20detail_3a_3adiriterstate_20_3e',['IntrusiveRefCntPtr&lt; detail::DirIterState &gt;',['../d5/d48/classllvm_1_1IntrusiveRefCntPtr.html',1,'llvm']]],
  ['intrusiverefcntptr_3c_20detail_3a_3arecdiriterstate_20_3e',['IntrusiveRefCntPtr&lt; detail::RecDirIterState &gt;',['../d5/d48/classllvm_1_1IntrusiveRefCntPtr.html',1,'llvm']]],
  ['intrusiverefcntptrinfo',['IntrusiveRefCntPtrInfo',['../d7/d4d/structllvm_1_1IntrusiveRefCntPtrInfo.html',1,'llvm']]],
  ['intrusiverefcntptrinfo_3c_20interceptrefcounted_20_3e',['IntrusiveRefCntPtrInfo&lt; InterceptRefCounted &gt;',['../d7/de8/structllvm_1_1IntrusiveRefCntPtrInfo_3_01InterceptRefCounted_01_4.html',1,'llvm']]],
  ['inttoptrinst',['IntToPtrInst',['../da/d8d/classllvm_1_1IntToPtrInst.html',1,'llvm']]],
  ['inverse',['Inverse',['../d3/d26/structllvm_1_1Inverse.html',1,'llvm']]],
  ['invokeinst',['InvokeInst',['../d3/ded/classllvm_1_1InvokeInst.html',1,'llvm']]],
  ['io',['IO',['../db/d8d/classllvm_1_1yaml_1_1IO.html',1,'llvm::yaml']]],
  ['iplist',['iplist',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20argument_20_3e',['iplist&lt; Argument &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20basicblock_20_3e',['iplist&lt; BasicBlock &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20function_20_3e',['iplist&lt; Function &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20globalalias_20_3e',['iplist&lt; GlobalAlias &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20globalvariable_20_3e',['iplist&lt; GlobalVariable &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20indexlistentry_20_3e',['iplist&lt; IndexListEntry &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20instruction_20_3e',['iplist&lt; Instruction &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20llvm_3a_3aaliasset_20_3e',['iplist&lt; llvm::AliasSet &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20llvm_3a_3aivstrideuse_20_3e',['iplist&lt; llvm::IVStrideUse &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20llvm_3a_3amcsectiondata_20_3e',['iplist&lt; llvm::MCSectionData &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20llvm_3a_3amcsymboldata_20_3e',['iplist&lt; llvm::MCSymbolData &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20llvm_3a_3arecyclerstruct_20_3e',['iplist&lt; llvm::RecyclerStruct &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20llvm_3a_3asdnode_20_3e',['iplist&lt; llvm::SDNode &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20machinebasicblock_20_3e',['iplist&lt; MachineBasicBlock &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20machineinstr_20_3e',['iplist&lt; MachineInstr &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20mcfragment_20_3e',['iplist&lt; MCFragment &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20namedmdnode_20_3e',['iplist&lt; NamedMDNode &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20nodety_20_3e',['iplist&lt; NodeTy &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['iplist&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20state_20_3e',['iplist&lt; State &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20token_20_3e',['iplist&lt; Token &gt;',['../d0/dc9/classllvm_1_1iplist.html',1,'llvm']]],
  ['ipo_5fext_5fiterator',['ipo_ext_iterator',['../d9/d1f/structllvm_1_1ipo__ext__iterator.html',1,'llvm']]],
  ['ipo_5fiterator',['ipo_iterator',['../d1/de9/structllvm_1_1ipo__iterator.html',1,'llvm']]],
  ['ipo_5fiterator_3c_20t_2c_20settype_2c_20true_20_3e',['ipo_iterator&lt; T, SetType, true &gt;',['../d1/de9/structllvm_1_1ipo__iterator.html',1,'llvm']]],
  ['irbuilder',['IRBuilder',['../d9/df8/classllvm_1_1IRBuilder.html',1,'llvm']]],
  ['irbuilder_3c_20true_2c_20targetfolder_20_3e',['IRBuilder&lt; true, TargetFolder &gt;',['../d9/df8/classllvm_1_1IRBuilder.html',1,'llvm']]],
  ['irbuilderbase',['IRBuilderBase',['../d4/db6/classllvm_1_1IRBuilderBase.html',1,'llvm']]],
  ['irbuilderdefaultinserter',['IRBuilderDefaultInserter',['../dd/d12/classllvm_1_1IRBuilderDefaultInserter.html',1,'llvm']]],
  ['irbuilderdefaultinserter_3c_20true_20_3e',['IRBuilderDefaultInserter&lt; true &gt;',['../dd/d12/classllvm_1_1IRBuilderDefaultInserter.html',1,'llvm']]],
  ['irobjectfile',['IRObjectFile',['../db/dfa/classllvm_1_1object_1_1IRObjectFile.html',1,'llvm::object']]],
  ['irreduciblegraph',['IrreducibleGraph',['../d8/dd2/structllvm_1_1bfi__detail_1_1IrreducibleGraph.html',1,'llvm::bfi_detail']]],
  ['irrnode',['IrrNode',['../db/d1f/structllvm_1_1bfi__detail_1_1IrreducibleGraph_1_1IrrNode.html',1,'llvm::bfi_detail::IrreducibleGraph']]],
  ['is_5fall_5fones',['is_all_ones',['../d8/da1/structllvm_1_1PatternMatch_1_1is__all__ones.html',1,'llvm::PatternMatch']]],
  ['is_5ferror_5fcode_5fenum_3c_20llvm_3a_3aerrc_20_3e',['is_error_code_enum&lt; llvm::errc &gt;',['../d9/dfc/structstd_1_1is__error__code__enum_3_01llvm_1_1errc_01_4.html',1,'std']]],
  ['is_5ferror_5fcode_5fenum_3c_20llvm_3a_3ainstrprof_5ferror_20_3e',['is_error_code_enum&lt; llvm::instrprof_error &gt;',['../db/dca/structstd_1_1is__error__code__enum_3_01llvm_1_1instrprof__error_01_4.html',1,'std']]],
  ['is_5ferror_5fcode_5fenum_3c_20llvm_3a_3aobj2yaml_5ferror_20_3e',['is_error_code_enum&lt; llvm::obj2yaml_error &gt;',['../d4/daf/structstd_1_1is__error__code__enum_3_01llvm_1_1obj2yaml__error_01_4.html',1,'std']]],
  ['is_5ferror_5fcode_5fenum_3c_20llvm_3a_3aobject_3a_3aobject_5ferror_20_3e',['is_error_code_enum&lt; llvm::object::object_error &gt;',['../d4/d88/structstd_1_1is__error__code__enum_3_01llvm_1_1object_1_1object__error_01_4.html',1,'std']]],
  ['is_5ferror_5fcode_5fenum_3c_20llvm_3a_3areadobj_5ferror_20_3e',['is_error_code_enum&lt; llvm::readobj_error &gt;',['../de/d85/structstd_1_1is__error__code__enum_3_01llvm_1_1readobj__error_01_4.html',1,'std']]],
  ['is_5fhashable_5fdata',['is_hashable_data',['../dd/d5f/structllvm_1_1hashing_1_1detail_1_1is__hashable__data.html',1,'llvm::hashing::detail']]],
  ['is_5fhashable_5fdata_3c_20largetestinteger_20_3e',['is_hashable_data&lt; LargeTestInteger &gt;',['../dd/dc9/structllvm_1_1hashing_1_1detail_1_1is__hashable__data_3_01LargeTestInteger_01_4.html',1,'llvm::hashing::detail']]],
  ['is_5fhashable_5fdata_3c_20std_3a_3apair_3c_20t_2c_20u_20_3e_20_3e',['is_hashable_data&lt; std::pair&lt; T, U &gt; &gt;',['../d2/d7a/structllvm_1_1hashing_1_1detail_1_1is__hashable__data_3_01std_1_1pair_3_01T_00_01U_01_4_01_4.html',1,'llvm::hashing::detail']]],
  ['is_5fintegral_5for_5fenum',['is_integral_or_enum',['../da/da9/classllvm_1_1is__integral__or__enum.html',1,'llvm']]],
  ['is_5fone',['is_one',['../d9/d3f/structllvm_1_1PatternMatch_1_1is__one.html',1,'llvm::PatternMatch']]],
  ['is_5fpointer',['is_pointer',['../de/d83/structtesting_1_1internal_1_1is__pointer.html',1,'testing::internal']]],
  ['is_5fpointer_3c_20t_20_2a_20_3e',['is_pointer&lt; T * &gt;',['../dc/d5b/structtesting_1_1internal_1_1is__pointer_3_01T_01_5_01_4.html',1,'testing::internal']]],
  ['is_5fpower2',['is_power2',['../d7/d7e/structllvm_1_1PatternMatch_1_1is__power2.html',1,'llvm::PatternMatch']]],
  ['is_5fsign_5fbit',['is_sign_bit',['../df/d5d/structllvm_1_1PatternMatch_1_1is__sign__bit.html',1,'llvm::PatternMatch']]],
  ['is_5fsimple_5ftype',['is_simple_type',['../d5/d0d/structllvm_1_1is__simple__type.html',1,'llvm']]],
  ['isa_5fimpl',['isa_impl',['../d5/dae/structllvm_1_1isa__impl.html',1,'llvm']]],
  ['isa_5fimpl_3c_20argument_2c_20value_20_3e',['isa_impl&lt; Argument, Value &gt;',['../d0/da2/structllvm_1_1isa__impl_3_01Argument_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20basicblock_2c_20value_20_3e',['isa_impl&lt; BasicBlock, Value &gt;',['../d2/dfa/structllvm_1_1isa__impl_3_01BasicBlock_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20constant_2c_20value_20_3e',['isa_impl&lt; Constant, Value &gt;',['../d3/da0/structllvm_1_1isa__impl_3_01Constant_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20foo_2c_20bar_20_3e',['isa_impl&lt; foo, bar &gt;',['../d8/d5b/structllvm_1_1isa__impl_3_01foo_00_01bar_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20function_2c_20value_20_3e',['isa_impl&lt; Function, Value &gt;',['../da/de4/structllvm_1_1isa__impl_3_01Function_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20globalalias_2c_20value_20_3e',['isa_impl&lt; GlobalAlias, Value &gt;',['../d9/d15/structllvm_1_1isa__impl_3_01GlobalAlias_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20globalobject_2c_20value_20_3e',['isa_impl&lt; GlobalObject, Value &gt;',['../d4/d01/structllvm_1_1isa__impl_3_01GlobalObject_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20globalvalue_2c_20value_20_3e',['isa_impl&lt; GlobalValue, Value &gt;',['../de/d0a/structllvm_1_1isa__impl_3_01GlobalValue_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20globalvariable_2c_20value_20_3e',['isa_impl&lt; GlobalVariable, Value &gt;',['../d5/d9a/structllvm_1_1isa__impl_3_01GlobalVariable_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20inlineasm_2c_20value_20_3e',['isa_impl&lt; InlineAsm, Value &gt;',['../db/dfe/structllvm_1_1isa__impl_3_01InlineAsm_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20instruction_2c_20value_20_3e',['isa_impl&lt; Instruction, Value &gt;',['../d9/d7b/structllvm_1_1isa__impl_3_01Instruction_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20mdnode_2c_20value_20_3e',['isa_impl&lt; MDNode, Value &gt;',['../db/d66/structllvm_1_1isa__impl_3_01MDNode_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20pointertype_2c_20type_20_3e',['isa_impl&lt; PointerType, Type &gt;',['../da/df8/structllvm_1_1isa__impl_3_01PointerType_00_01Type_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20to_2c_20from_2c_20typename_20std_3a_3aenable_5fif_3c_20std_3a_3ais_5fbase_5fof_3c_20to_2c_20from_20_3e_3a_3avalue_20_3e_3a_3atype_20_3e',['isa_impl&lt; To, From, typename std::enable_if&lt; std::is_base_of&lt; To, From &gt;::value &gt;::type &gt;',['../d1/df1/structllvm_1_1isa__impl_3_01To_00_01From_00_01typename_01std_1_1enable__if_3_01std_1_1is__base__857707abab84a012af2c502e6563e526.html',1,'llvm']]],
  ['isa_5fimpl_5fcl',['isa_impl_cl',['../dd/d24/structllvm_1_1isa__impl__cl.html',1,'llvm']]],
  ['isa_5fimpl_5fcl_3c_20to_2c_20const_20from_20_2a_20_3e',['isa_impl_cl&lt; To, const From * &gt;',['../d1/d54/structllvm_1_1isa__impl__cl_3_01To_00_01const_01From_01_5_01_4.html',1,'llvm']]],
  ['isa_5fimpl_5fcl_3c_20to_2c_20const_20from_20_2aconst_20_20_3e',['isa_impl_cl&lt; To, const From *const  &gt;',['../d2/ddc/structllvm_1_1isa__impl__cl_3_01To_00_01const_01From_01_5const_01_01_4.html',1,'llvm']]],
  ['isa_5fimpl_5fcl_3c_20to_2c_20const_20from_20_3e',['isa_impl_cl&lt; To, const From &gt;',['../d2/dbf/structllvm_1_1isa__impl__cl_3_01To_00_01const_01From_01_4.html',1,'llvm']]],
  ['isa_5fimpl_5fcl_3c_20to_2c_20from_20_2a_20_3e',['isa_impl_cl&lt; To, From * &gt;',['../db/d5e/structllvm_1_1isa__impl__cl_3_01To_00_01From_01_5_01_4.html',1,'llvm']]],
  ['isa_5fimpl_5fcl_3c_20to_2c_20from_20_2aconst_20_20_3e',['isa_impl_cl&lt; To, From *const  &gt;',['../d3/d14/structllvm_1_1isa__impl__cl_3_01To_00_01From_01_5const_01_01_4.html',1,'llvm']]],
  ['isa_5fimpl_5fwrap',['isa_impl_wrap',['../d8/d34/structllvm_1_1isa__impl__wrap.html',1,'llvm']]],
  ['isa_5fimpl_5fwrap_3c_20to_2c_20fromty_2c_20fromty_20_3e',['isa_impl_wrap&lt; To, FromTy, FromTy &gt;',['../d6/d2a/structllvm_1_1isa__impl__wrap_3_01To_00_01FromTy_00_01FromTy_01_4.html',1,'llvm']]],
  ['isaprotocolmessage',['IsAProtocolMessage',['../d9/d92/structtesting_1_1internal_1_1IsAProtocolMessage.html',1,'testing::internal']]],
  ['isatendt',['IsAtEndT',['../d4/d27/structllvm_1_1LazyCallGraph_1_1postorder__scc__iterator_1_1IsAtEndT.html',1,'llvm::LazyCallGraph::postorder_scc_iterator']]],
  ['isbmapper',['ISBMapper',['../df/d48/structllvm_1_1AArch64ISB_1_1ISBMapper.html',1,'llvm::AArch64ISB']]],
  ['isinnerunion',['IsInnerUnion',['../d4/d3f/structllvm_1_1PointerUnion3_1_1IsInnerUnion.html',1,'llvm::PointerUnion3']]],
  ['ispodlike',['isPodLike',['../d3/db9/structllvm_1_1isPodLike.html',1,'llvm']]],
  ['ispodlike_3c_20arrayref_3c_20t_20_3e_20_3e',['isPodLike&lt; ArrayRef&lt; T &gt; &gt;',['../db/d3b/structllvm_1_1isPodLike_3_01ArrayRef_3_01T_01_4_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20assertingvh_3c_20t_20_3e_20_3e',['isPodLike&lt; AssertingVH&lt; T &gt; &gt;',['../d0/d8e/structllvm_1_1isPodLike_3_01AssertingVH_3_01T_01_4_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20bfi_5fdetail_3a_3ablockmass_20_3e',['isPodLike&lt; bfi_detail::BlockMass &gt;',['../d8/d6e/structllvm_1_1isPodLike_3_01bfi__detail_1_1BlockMass_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20bitcodeabbrevop_20_3e',['isPodLike&lt; BitCodeAbbrevOp &gt;',['../dd/d43/structllvm_1_1isPodLike_3_01BitCodeAbbrevOp_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20identifyingpassptr_20_3e',['isPodLike&lt; IdentifyingPassPtr &gt;',['../d3/dea/structllvm_1_1isPodLike_3_01IdentifyingPassPtr_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20immutablelist_3c_20t_20_3e_20_3e',['isPodLike&lt; ImmutableList&lt; T &gt; &gt;',['../d7/d9e/structllvm_1_1isPodLike_3_01ImmutableList_3_01T_01_4_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20mcoperand_20_3e',['isPodLike&lt; MCOperand &gt;',['../df/dc9/structllvm_1_1isPodLike_3_01MCOperand_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20optional_3c_20t_20_3e_20_3e',['isPodLike&lt; Optional&lt; T &gt; &gt;',['../d9/d67/structllvm_1_1isPodLike_3_01Optional_3_01T_01_4_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20pointerintpair_3c_20pointerty_2c_20intbits_2c_20inttype_20_3e_20_3e',['isPodLike&lt; PointerIntPair&lt; PointerTy, IntBits, IntType &gt; &gt;',['../de/d56/structllvm_1_1isPodLike_3_01PointerIntPair_3_01PointerTy_00_01IntBits_00_01IntType_01_4_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20pressurechange_20_3e',['isPodLike&lt; PressureChange &gt;',['../db/d94/structllvm_1_1isPodLike_3_01PressureChange_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20scalednumber_3c_20t_20_3e_20_3e',['isPodLike&lt; ScaledNumber&lt; T &gt; &gt;',['../d0/d60/structllvm_1_1isPodLike_3_01ScaledNumber_3_01T_01_4_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20sdep_20_3e',['isPodLike&lt; SDep &gt;',['../db/df4/structllvm_1_1isPodLike_3_01SDep_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20sdvalue_20_3e',['isPodLike&lt; SDValue &gt;',['../dd/d19/structllvm_1_1isPodLike_3_01SDValue_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20slice_20_3e',['isPodLike&lt; Slice &gt;',['../dc/df4/structllvm_1_1isPodLike_3_01Slice_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20slotindex_20_3e',['isPodLike&lt; SlotIndex &gt;',['../d0/d55/structllvm_1_1isPodLike_3_01SlotIndex_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20std_3a_3apair_3c_20t_2c_20u_20_3e_20_3e',['isPodLike&lt; std::pair&lt; T, U &gt; &gt;',['../da/dbb/structllvm_1_1isPodLike_3_01std_1_1pair_3_01T_00_01U_01_4_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20stringref_20_3e',['isPodLike&lt; StringRef &gt;',['../dc/d56/structllvm_1_1isPodLike_3_01StringRef_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20succiterator_3c_20t_2c_20u_20_3e_20_3e',['isPodLike&lt; SuccIterator&lt; T, U &gt; &gt;',['../dd/d09/structllvm_1_1isPodLike_3_01SuccIterator_3_01T_00_01U_01_4_01_4.html',1,'llvm']]],
  ['ispt1',['IsPT1',['../d0/df1/structllvm_1_1PointerUnion_1_1IsPT1.html',1,'llvm::PointerUnion']]],
  ['ispt2',['IsPT2',['../db/d4b/structllvm_1_1PointerUnion_1_1IsPT2.html',1,'llvm::PointerUnion']]],
  ['ispt3',['IsPT3',['../db/d54/structllvm_1_1PointerUnion3_1_1IsPT3.html',1,'llvm::PointerUnion3']]],
  ['item',['Item',['../da/da2/classllvm_1_1OnDiskChainedHashTableGenerator_1_1Item.html',1,'llvm::OnDiskChainedHashTableGenerator']]],
  ['iterator',['iterator',['../dd/d14/classllvm_1_1LazyCallGraph_1_1iterator.html',1,'llvm::LazyCallGraph']]],
  ['iterator',['iterator',['../dc/da1/classllvm_1_1ImmutableMap_1_1iterator.html',1,'llvm::ImmutableMap']]],
  ['iterator',['Iterator',['../d7/d78/classllvm_1_1DenseSet_1_1Iterator.html',1,'llvm::DenseSet']]],
  ['iterator',['iterator',['../d7/de0/classllvm_1_1TargetRegistry_1_1iterator.html',1,'llvm::TargetRegistry']]],
  ['iterator',['iterator',['../d1/de3/classllvm_1_1ImmutableMapRef_1_1iterator.html',1,'llvm::ImmutableMapRef']]],
  ['iterator',['iterator',['../d4/d30/classllvm_1_1ImmutableSetRef_1_1iterator.html',1,'llvm::ImmutableSetRef']]],
  ['iterator',['iterator',['../df/d8c/classllvm_1_1ImmutableList_1_1iterator.html',1,'llvm::ImmutableList']]],
  ['iterator',['iterator',['../d8/d73/classllvm_1_1AliasSet_1_1iterator.html',1,'llvm::AliasSet']]],
  ['iterator',['iterator',['../da/d13/classllvm_1_1ImmutableSet_1_1iterator.html',1,'llvm::ImmutableSet']]],
  ['iterator',['iterator',['../d4/d42/classllvm_1_1OnDiskChainedHashTable_1_1iterator.html',1,'llvm::OnDiskChainedHashTable']]],
  ['iterator',['iterator',['../dd/d85/classllvm_1_1IntervalMap_1_1iterator.html',1,'llvm::IntervalMap']]],
  ['iterator',['iterator',['../d2/d20/classllvm_1_1Registry_1_1iterator.html',1,'llvm::Registry']]],
  ['iterator_5fadaptor_5fbase',['iterator_adaptor_base',['../d9/d02/classllvm_1_1iterator__adaptor__base.html',1,'llvm']]],
  ['iterator_5fadaptor_5fbase_3c_20iterator_2c_20nodevectorimplt_3a_3aiterator_2c_20std_3a_3aforward_5fiterator_5ftag_2c_20node_20_3e',['iterator_adaptor_base&lt; iterator, NodeVectorImplT::iterator, std::forward_iterator_tag, Node &gt;',['../d9/d02/classllvm_1_1iterator__adaptor__base.html',1,'llvm']]],
  ['iterator_5fadaptor_5fbase_3c_20pointee_5fiterator_3c_20wrappediteratort_20_3e_2c_20wrappediteratort_2c_20std_3a_3aiterator_5ftraits_3c_20wrappediteratort_20_3e_3a_3aiterator_5fcategory_2c_20t_20_3e',['iterator_adaptor_base&lt; pointee_iterator&lt; WrappedIteratorT &gt;, WrappedIteratorT, std::iterator_traits&lt; WrappedIteratorT &gt;::iterator_category, T &gt;',['../d9/d02/classllvm_1_1iterator__adaptor__base.html',1,'llvm']]],
  ['iterator_5fadaptor_5fbase_3c_20value_5fop_5fiterator_2c_20op_5fiterator_2c_20std_3a_3arandom_5faccess_5fiterator_5ftag_2c_20value_20_2a_2c_20ptrdiff_5ft_2c_20value_20_2a_2c_20value_20_2a_20_3e',['iterator_adaptor_base&lt; value_op_iterator, op_iterator, std::random_access_iterator_tag, Value *, ptrdiff_t, Value *, Value * &gt;',['../d9/d02/classllvm_1_1iterator__adaptor__base.html',1,'llvm']]],
  ['iterator_5fbase',['iterator_base',['../da/d45/classllvm_1_1SparseMultiSet_1_1iterator__base.html',1,'llvm::SparseMultiSet']]],
  ['iterator_5ffacade_5fbase',['iterator_facade_base',['../df/de3/classllvm_1_1iterator__facade__base.html',1,'llvm']]],
  ['iterator_5ffacade_5fbase_3c_20iterator_2c_20std_3a_3aforward_5fiterator_5ftag_2c_20node_2c_20typename_20std_3a_3aiterator_5ftraits_3c_20nodevectorimplt_3a_3aiterator_20_3e_3a_3adifference_5ftype_2c_20node_20_2a_2c_20node_20_26_20_3e',['iterator_facade_base&lt; iterator, std::forward_iterator_tag, Node, typename std::iterator_traits&lt; NodeVectorImplT::iterator &gt;::difference_type, Node *, Node &amp; &gt;',['../df/de3/classllvm_1_1iterator__facade__base.html',1,'llvm']]],
  ['iterator_5ffacade_5fbase_3c_20pointee_5fiterator_3c_20wrappediteratort_20_3e_2c_20std_3a_3aiterator_5ftraits_3c_20wrappediteratort_20_3e_3a_3aiterator_5fcategory_2c_20t_2c_20typename_20std_3a_3aiterator_5ftraits_3c_20wrappediteratort_20_3e_3a_3adifference_5ftype_2c_20t_20_2a_2c_20t_20_26_20_3e',['iterator_facade_base&lt; pointee_iterator&lt; WrappedIteratorT &gt;, std::iterator_traits&lt; WrappedIteratorT &gt;::iterator_category, T, typename std::iterator_traits&lt; WrappedIteratorT &gt;::difference_type, T *, T &amp; &gt;',['../df/de3/classllvm_1_1iterator__facade__base.html',1,'llvm']]],
  ['iterator_5ffacade_5fbase_3c_20postorder_5fscc_5fiterator_2c_20std_3a_3aforward_5fiterator_5ftag_2c_20scc_20_3e',['iterator_facade_base&lt; postorder_scc_iterator, std::forward_iterator_tag, SCC &gt;',['../df/de3/classllvm_1_1iterator__facade__base.html',1,'llvm']]],
  ['iterator_5ffacade_5fbase_3c_20scc_5fiterator_3c_20grapht_2c_20gt_20_3e_2c_20std_3a_3aforward_5fiterator_5ftag_2c_20const_20std_3a_3avector_3c_20gt_3a_3anodetype_20_2a_20_3e_2c_20ptrdiff_5ft_20_3e',['iterator_facade_base&lt; scc_iterator&lt; GraphT, GT &gt;, std::forward_iterator_tag, const std::vector&lt; GT::NodeType * &gt;, ptrdiff_t &gt;',['../df/de3/classllvm_1_1iterator__facade__base.html',1,'llvm']]],
  ['iterator_5ffacade_5fbase_3c_20value_5fop_5fiterator_2c_20std_3a_3arandom_5faccess_5fiterator_5ftag_2c_20value_20_2a_2c_20ptrdiff_5ft_2c_20value_20_2a_2c_20value_20_2a_20_3e',['iterator_facade_base&lt; value_op_iterator, std::random_access_iterator_tag, Value *, ptrdiff_t, Value *, Value * &gt;',['../df/de3/classllvm_1_1iterator__facade__base.html',1,'llvm']]],
  ['iterator_5frange',['iterator_range',['../de/dfa/classllvm_1_1iterator__range.html',1,'llvm']]],
  ['iteratortraits',['IteratorTraits',['../d5/dc7/structtesting_1_1internal_1_1IteratorTraits.html',1,'testing::internal']]],
  ['iteratortraits_3c_20const_20t_20_2a_20_3e',['IteratorTraits&lt; const T * &gt;',['../da/da3/structtesting_1_1internal_1_1IteratorTraits_3_01const_01T_01_5_01_4.html',1,'testing::internal']]],
  ['iteratortraits_3c_20t_20_2a_20_3e',['IteratorTraits&lt; T * &gt;',['../d9/d76/structtesting_1_1internal_1_1IteratorTraits_3_01T_01_5_01_4.html',1,'testing::internal']]],
  ['iterrecord',['IterRecord',['../da/d1a/structllvm_1_1TGParser_1_1IterRecord.html',1,'llvm::TGParser']]],
  ['ivstrideuse',['IVStrideUse',['../da/d71/classllvm_1_1IVStrideUse.html',1,'llvm']]],
  ['ivusers',['IVUsers',['../d5/d5a/classllvm_1_1IVUsers.html',1,'llvm']]],
  ['ivvisitor',['IVVisitor',['../df/dc8/classllvm_1_1IVVisitor.html',1,'llvm']]]
];
