var searchData=
[
  ['r600instrinfo',['R600InstrInfo',['../de/ded/classllvm_1_1R600InstrInfo.html',1,'llvm']]],
  ['r600machinefunctioninfo',['R600MachineFunctionInfo',['../d7/dfe/classllvm_1_1R600MachineFunctionInfo.html',1,'llvm']]],
  ['r600registerinfo',['R600RegisterInfo',['../d4/de6/structllvm_1_1R600RegisterInfo.html',1,'llvm']]],
  ['r600schedstrategy',['R600SchedStrategy',['../dd/d5c/classllvm_1_1R600SchedStrategy.html',1,'llvm']]],
  ['r600targetlowering',['R600TargetLowering',['../d7/d12/classllvm_1_1R600TargetLowering.html',1,'llvm']]],
  ['ram',['RAM',['../d8/d23/classlegup_1_1RAM.html',1,'legup']]],
  ['random',['Random',['../dc/d5a/classtesting_1_1internal_1_1Random.html',1,'testing::internal']]],
  ['randomnumbergenerator',['RandomNumberGenerator',['../de/d32/classllvm_1_1RandomNumberGenerator.html',1,'llvm']]],
  ['range',['Range',['../d9/dea/structllvm_1_1DWARFDebugAranges_1_1Range.html',1,'llvm::DWARFDebugAranges']]],
  ['range',['Range',['../de/d4c/classlegup_1_1Range.html',1,'legup']]],
  ['rangeendpoint',['RangeEndpoint',['../d4/dde/structllvm_1_1DWARFDebugAranges_1_1RangeEndpoint.html',1,'llvm::DWARFDebugAranges']]],
  ['rangelistentry',['RangeListEntry',['../d2/d9d/structllvm_1_1DWARFDebugRangeList_1_1RangeListEntry.html',1,'llvm::DWARFDebugRangeList']]],
  ['rangespan',['RangeSpan',['../d1/d5f/classllvm_1_1RangeSpan.html',1,'llvm']]],
  ['rangespanlist',['RangeSpanList',['../d1/dc0/classllvm_1_1RangeSpanList.html',1,'llvm']]],
  ['raw_5ffd_5fostream',['raw_fd_ostream',['../d3/dd4/classllvm_1_1raw__fd__ostream.html',1,'llvm']]],
  ['raw_5fnull_5fostream',['raw_null_ostream',['../d7/d0a/classllvm_1_1raw__null__ostream.html',1,'llvm']]],
  ['raw_5fos_5fostream',['raw_os_ostream',['../dd/dc3/classllvm_1_1raw__os__ostream.html',1,'llvm']]],
  ['raw_5fostream',['raw_ostream',['../d7/d03/classllvm_1_1raw__ostream.html',1,'llvm']]],
  ['raw_5fstring_5fostream',['raw_string_ostream',['../dd/dd0/classllvm_1_1raw__string__ostream.html',1,'llvm']]],
  ['raw_5fsvector_5fostream',['raw_svector_ostream',['../da/df4/classllvm_1_1raw__svector__ostream.html',1,'llvm']]],
  ['rawcontentsection',['RawContentSection',['../d8/d3f/structllvm_1_1ELFYAML_1_1RawContentSection.html',1,'llvm::ELFYAML']]],
  ['rawheader',['RawHeader',['../d7/d6a/structllvm_1_1RawInstrProfReader_1_1RawHeader.html',1,'llvm::RawInstrProfReader']]],
  ['rawinstrprofreader',['RawInstrProfReader',['../da/d23/classllvm_1_1RawInstrProfReader.html',1,'llvm']]],
  ['rcinfo',['RCInfo',['../df/dce/structllvm_1_1RegisterClassInfo_1_1RCInfo.html',1,'llvm::RegisterClassInfo']]],
  ['re',['RE',['../d0/d6d/classtesting_1_1internal_1_1RE.html',1,'testing::internal']]],
  ['re_5fguts',['re_guts',['../dc/d7c/structre__guts.html',1,'']]],
  ['readyqueue',['ReadyQueue',['../dc/daf/classllvm_1_1ReadyQueue.html',1,'llvm']]],
  ['realmetricvalue',['RealMetricValue',['../d6/d64/classlit_1_1Test_1_1RealMetricValue.html',1,'lit::Test']]],
  ['realpredicate',['RealPredicate',['../dd/d4a/classllvm_1_1core_1_1RealPredicate.html',1,'llvm::core']]],
  ['recdiriterstate',['RecDirIterState',['../da/dd7/structllvm_1_1sys_1_1fs_1_1detail_1_1RecDirIterState.html',1,'llvm::sys::fs::detail']]],
  ['recognizableinstr',['RecognizableInstr',['../db/d1a/classllvm_1_1X86Disassembler_1_1RecognizableInstr.html',1,'llvm::X86Disassembler']]],
  ['record',['Record',['../d6/dd1/classllvm_1_1Record.html',1,'llvm']]],
  ['recordchildmatcher',['RecordChildMatcher',['../df/d7c/classllvm_1_1RecordChildMatcher.html',1,'llvm']]],
  ['recordkeeper',['RecordKeeper',['../d5/dfb/classllvm_1_1RecordKeeper.html',1,'llvm']]],
  ['recordmatcher',['RecordMatcher',['../d6/dcb/classllvm_1_1RecordMatcher.html',1,'llvm']]],
  ['recordmemrefmatcher',['RecordMemRefMatcher',['../db/d46/classllvm_1_1RecordMemRefMatcher.html',1,'llvm']]],
  ['recordparts',['RecordParts',['../df/d7b/structllvm_1_1LessRecordRegister_1_1RecordParts.html',1,'llvm::LessRecordRegister']]],
  ['recordrecty',['RecordRecTy',['../d4/db9/classllvm_1_1RecordRecTy.html',1,'llvm']]],
  ['recordstreamer',['RecordStreamer',['../d6/def/classllvm_1_1RecordStreamer.html',1,'llvm']]],
  ['recordval',['RecordVal',['../dd/dd0/classllvm_1_1RecordVal.html',1,'llvm']]],
  ['recty',['RecTy',['../d6/d8b/classllvm_1_1RecTy.html',1,'llvm']]],
  ['recursive_5fdirectory_5fiterator',['recursive_directory_iterator',['../d4/d9b/classllvm_1_1sys_1_1fs_1_1recursive__directory__iterator.html',1,'llvm::sys::fs']]],
  ['recycler',['Recycler',['../df/ddc/classllvm_1_1Recycler.html',1,'llvm']]],
  ['recycler_3c_20llvm_3a_3amachinebasicblock_20_3e',['Recycler&lt; llvm::MachineBasicBlock &gt;',['../df/ddc/classllvm_1_1Recycler.html',1,'llvm']]],
  ['recycler_3c_20llvm_3a_3amachineinstr_20_3e',['Recycler&lt; llvm::MachineInstr &gt;',['../df/ddc/classllvm_1_1Recycler.html',1,'llvm']]],
  ['recycler_3c_20sdnode_2c_20size_2c_20align_20_3e',['Recycler&lt; SDNode, Size, Align &gt;',['../df/ddc/classllvm_1_1Recycler.html',1,'llvm']]],
  ['recyclerstruct',['RecyclerStruct',['../d0/da7/structllvm_1_1RecyclerStruct.html',1,'llvm']]],
  ['recyclingallocator',['RecyclingAllocator',['../da/d57/classllvm_1_1RecyclingAllocator.html',1,'llvm']]],
  ['recyclingallocator_3c_20bumpptrallocator_2c_20sdnode_2c_20sizeof_28largestsdnode_29_2c_20alignof_3c_20mostalignedsdnode_20_3e_3a_3aalignment_20_3e',['RecyclingAllocator&lt; BumpPtrAllocator, SDNode, sizeof(LargestSDNode), AlignOf&lt; MostAlignedSDNode &gt;::Alignment &gt;',['../da/d57/classllvm_1_1RecyclingAllocator.html',1,'llvm']]],
  ['reducepasslist',['ReducePassList',['../d2/ddb/classllvm_1_1ReducePassList.html',1,'llvm']]],
  ['refcountedbase',['RefCountedBase',['../d9/d0c/classllvm_1_1RefCountedBase.html',1,'llvm']]],
  ['refcountedbase_3c_20diriterstate_20_3e',['RefCountedBase&lt; DirIterState &gt;',['../d9/d0c/classllvm_1_1RefCountedBase.html',1,'llvm']]],
  ['refcountedbase_3c_20interceptrefcounted_20_3e',['RefCountedBase&lt; InterceptRefCounted &gt;',['../d9/d0c/classllvm_1_1RefCountedBase.html',1,'llvm']]],
  ['refcountedbase_3c_20recdiriterstate_20_3e',['RefCountedBase&lt; RecDirIterState &gt;',['../d9/d0c/classllvm_1_1RefCountedBase.html',1,'llvm']]],
  ['refcountedbase_3c_20simplerefcounted_20_3e',['RefCountedBase&lt; SimpleRefCounted &gt;',['../d9/d0c/classllvm_1_1RefCountedBase.html',1,'llvm']]],
  ['refcountedbasevptr',['RefCountedBaseVPTR',['../d5/d09/classllvm_1_1RefCountedBaseVPTR.html',1,'llvm']]],
  ['reference',['reference',['../d7/d0b/classllvm_1_1PackedVector_1_1reference.html',1,'llvm::PackedVector']]],
  ['reference',['reference',['../db/d06/classllvm_1_1SmallBitVector_1_1reference.html',1,'llvm::SmallBitVector']]],
  ['reference',['reference',['../da/d4e/classllvm_1_1BitVector_1_1reference.html',1,'llvm::BitVector']]],
  ['referencestorage',['ReferenceStorage',['../df/d4e/classllvm_1_1ReferenceStorage.html',1,'llvm']]],
  ['regallocbase',['RegAllocBase',['../d0/d2e/classllvm_1_1RegAllocBase.html',1,'llvm']]],
  ['regallocsolverimpl',['RegAllocSolverImpl',['../d3/de1/classPBQP_1_1RegAlloc_1_1RegAllocSolverImpl.html',1,'PBQP::RegAlloc']]],
  ['regclassweight',['RegClassWeight',['../d7/d01/structllvm_1_1RegClassWeight.html',1,'llvm']]],
  ['regdefiter',['RegDefIter',['../d3/d5d/classllvm_1_1ScheduleDAGSDNodes_1_1RegDefIter.html',1,'llvm::ScheduleDAGSDNodes']]],
  ['regex',['Regex',['../dd/dcc/classllvm_1_1Regex.html',1,'llvm']]],
  ['region',['Region',['../d8/d1f/classllvm_1_1Region.html',1,'llvm']]],
  ['regionbase',['RegionBase',['../dc/d32/classllvm_1_1RegionBase.html',1,'llvm']]],
  ['regionbase_3c_20regiontraits_3c_20function_20_3e_20_3e',['RegionBase&lt; RegionTraits&lt; Function &gt; &gt;',['../dc/d32/classllvm_1_1RegionBase.html',1,'llvm']]],
  ['regionbase_3c_20regiontraits_3c_20machinefunction_20_3e_20_3e',['RegionBase&lt; RegionTraits&lt; MachineFunction &gt; &gt;',['../dc/d32/classllvm_1_1RegionBase.html',1,'llvm']]],
  ['regioninfo',['RegionInfo',['../da/d2d/classllvm_1_1RegionInfo.html',1,'llvm']]],
  ['regioninfobase',['RegionInfoBase',['../d7/dee/classllvm_1_1RegionInfoBase.html',1,'llvm']]],
  ['regioninfobase_3c_20regiontraits_3c_20function_20_3e_20_3e',['RegionInfoBase&lt; RegionTraits&lt; Function &gt; &gt;',['../d7/dee/classllvm_1_1RegionInfoBase.html',1,'llvm']]],
  ['regioninfobase_3c_20regiontraits_3c_20machinefunction_20_3e_20_3e',['RegionInfoBase&lt; RegionTraits&lt; MachineFunction &gt; &gt;',['../d7/dee/classllvm_1_1RegionInfoBase.html',1,'llvm']]],
  ['regioninfopass',['RegionInfoPass',['../d5/d17/classllvm_1_1RegionInfoPass.html',1,'llvm']]],
  ['regionnode',['RegionNode',['../db/d42/classllvm_1_1RegionNode.html',1,'llvm']]],
  ['regionnodebase',['RegionNodeBase',['../d6/dbd/classllvm_1_1RegionNodeBase.html',1,'llvm']]],
  ['regionnodebase_3c_20regiontraits_3c_20function_20_3e_20_3e',['RegionNodeBase&lt; RegionTraits&lt; Function &gt; &gt;',['../d6/dbd/classllvm_1_1RegionNodeBase.html',1,'llvm']]],
  ['regionnodebase_3c_20regiontraits_3c_20machinefunction_20_3e_20_3e',['RegionNodeBase&lt; RegionTraits&lt; MachineFunction &gt; &gt;',['../d6/dbd/classllvm_1_1RegionNodeBase.html',1,'llvm']]],
  ['regionpass',['RegionPass',['../dd/d81/classllvm_1_1RegionPass.html',1,'llvm']]],
  ['regionpressure',['RegionPressure',['../d1/d4e/structllvm_1_1RegionPressure.html',1,'llvm']]],
  ['regiontraits',['RegionTraits',['../de/dd0/structllvm_1_1RegionTraits.html',1,'llvm']]],
  ['regiontraits_3c_20function_20_3e',['RegionTraits&lt; Function &gt;',['../d0/df1/structllvm_1_1RegionTraits_3_01Function_01_4.html',1,'llvm']]],
  ['regiontraits_3c_20machinefunction_20_3e',['RegionTraits&lt; MachineFunction &gt;',['../dc/d09/structllvm_1_1RegionTraits_3_01MachineFunction_01_4.html',1,'llvm']]],
  ['registeragbase',['RegisterAGBase',['../d3/dcd/classllvm_1_1RegisterAGBase.html',1,'llvm']]],
  ['registeranalysisgroup',['RegisterAnalysisGroup',['../d3/d6d/structllvm_1_1RegisterAnalysisGroup.html',1,'llvm']]],
  ['registerasmprinter',['RegisterAsmPrinter',['../d3/d5d/structllvm_1_1RegisterAsmPrinter.html',1,'llvm']]],
  ['registerclassinfo',['RegisterClassInfo',['../df/dd0/classllvm_1_1RegisterClassInfo.html',1,'llvm']]],
  ['registermasksdnode',['RegisterMaskSDNode',['../d3/dae/classllvm_1_1RegisterMaskSDNode.html',1,'llvm']]],
  ['registermcasmbackend',['RegisterMCAsmBackend',['../d9/d2f/structllvm_1_1RegisterMCAsmBackend.html',1,'llvm']]],
  ['registermcasminfo',['RegisterMCAsmInfo',['../d4/d06/structllvm_1_1RegisterMCAsmInfo.html',1,'llvm']]],
  ['registermcasminfofn',['RegisterMCAsmInfoFn',['../d2/d3e/structllvm_1_1RegisterMCAsmInfoFn.html',1,'llvm']]],
  ['registermcasmparser',['RegisterMCAsmParser',['../d7/d65/structllvm_1_1RegisterMCAsmParser.html',1,'llvm']]],
  ['registermccodeemitter',['RegisterMCCodeEmitter',['../db/d85/structllvm_1_1RegisterMCCodeEmitter.html',1,'llvm']]],
  ['registermccodegeninfo',['RegisterMCCodeGenInfo',['../d9/d7b/structllvm_1_1RegisterMCCodeGenInfo.html',1,'llvm']]],
  ['registermccodegeninfofn',['RegisterMCCodeGenInfoFn',['../dc/ddf/structllvm_1_1RegisterMCCodeGenInfoFn.html',1,'llvm']]],
  ['registermcinstranalysis',['RegisterMCInstrAnalysis',['../de/db9/structllvm_1_1RegisterMCInstrAnalysis.html',1,'llvm']]],
  ['registermcinstranalysisfn',['RegisterMCInstrAnalysisFn',['../d5/d0f/structllvm_1_1RegisterMCInstrAnalysisFn.html',1,'llvm']]],
  ['registermcinstrinfo',['RegisterMCInstrInfo',['../d2/d9e/structllvm_1_1RegisterMCInstrInfo.html',1,'llvm']]],
  ['registermcinstrinfofn',['RegisterMCInstrInfoFn',['../d2/d53/structllvm_1_1RegisterMCInstrInfoFn.html',1,'llvm']]],
  ['registermcreginfo',['RegisterMCRegInfo',['../d3/da5/structllvm_1_1RegisterMCRegInfo.html',1,'llvm']]],
  ['registermcreginfofn',['RegisterMCRegInfoFn',['../dd/d26/structllvm_1_1RegisterMCRegInfoFn.html',1,'llvm']]],
  ['registermcsubtargetinfo',['RegisterMCSubtargetInfo',['../d9/d28/structllvm_1_1RegisterMCSubtargetInfo.html',1,'llvm']]],
  ['registermcsubtargetinfofn',['RegisterMCSubtargetInfoFn',['../d7/d10/structllvm_1_1RegisterMCSubtargetInfoFn.html',1,'llvm']]],
  ['registeroperands',['RegisterOperands',['../d7/dfe/classRegisterOperands.html',1,'']]],
  ['registerpass',['RegisterPass',['../d4/d7a/structllvm_1_1RegisterPass.html',1,'llvm']]],
  ['registerpassparser',['RegisterPassParser',['../d1/d5d/classllvm_1_1RegisterPassParser.html',1,'llvm']]],
  ['registerpressure',['RegisterPressure',['../dd/dfb/structllvm_1_1RegisterPressure.html',1,'llvm']]],
  ['registerreference',['RegisterReference',['../dc/d00/structllvm_1_1AggressiveAntiDepState_1_1RegisterReference.html',1,'llvm::AggressiveAntiDepState']]],
  ['registerregalloc',['RegisterRegAlloc',['../d5/d44/classllvm_1_1RegisterRegAlloc.html',1,'llvm']]],
  ['registerscheduler',['RegisterScheduler',['../d8/dd2/classllvm_1_1RegisterScheduler.html',1,'llvm']]],
  ['registersdnode',['RegisterSDNode',['../d8/d8b/classllvm_1_1RegisterSDNode.html',1,'llvm']]],
  ['registerstandardpasses',['RegisterStandardPasses',['../d5/d4e/structllvm_1_1RegisterStandardPasses.html',1,'llvm']]],
  ['registertarget',['RegisterTarget',['../d2/db1/structllvm_1_1RegisterTarget.html',1,'llvm']]],
  ['registertargetmachine',['RegisterTargetMachine',['../d3/d58/structllvm_1_1RegisterTargetMachine.html',1,'llvm']]],
  ['registry',['Registry',['../df/d83/classllvm_1_1Registry.html',1,'llvm']]],
  ['registryparser',['RegistryParser',['../db/d4a/classllvm_1_1RegistryParser.html',1,'llvm']]],
  ['registrytraits',['RegistryTraits',['../d2/d17/classllvm_1_1RegistryTraits.html',1,'llvm']]],
  ['regop',['RegOp',['../d7/d3e/structllvm_1_1X86Operand_1_1RegOp.html',1,'llvm::X86Operand']]],
  ['regpressuredelta',['RegPressureDelta',['../de/d14/structllvm_1_1RegPressureDelta.html',1,'llvm']]],
  ['regpressuretracker',['RegPressureTracker',['../d6/d7c/classllvm_1_1RegPressureTracker.html',1,'llvm']]],
  ['regscavenger',['RegScavenger',['../d9/d9a/classllvm_1_1RegScavenger.html',1,'llvm']]],
  ['regspilltracker',['RegSpillTracker',['../db/ded/structllvm_1_1SIMachineFunctionInfo_1_1RegSpillTracker.html',1,'llvm::SIMachineFunctionInfo']]],
  ['regunit',['RegUnit',['../d8/da8/structllvm_1_1RegUnit.html',1,'llvm']]],
  ['regunitinfo',['RegUnitInfo',['../d6/da7/structllvm_1_1InterferenceCache_1_1Entry_1_1RegUnitInfo.html',1,'llvm::InterferenceCache::Entry']]],
  ['regunitset',['RegUnitSet',['../da/d12/structllvm_1_1RegUnitSet.html',1,'llvm']]],
  ['relocation',['relocation',['../d7/df8/structllvm_1_1COFF_1_1relocation.html',1,'llvm::COFF']]],
  ['relocation',['Relocation',['../d6/de7/classllvm_1_1object_1_1Relocation.html',1,'llvm::object']]],
  ['relocation',['Relocation',['../df/da2/structllvm_1_1COFFYAML_1_1Relocation.html',1,'llvm::COFFYAML']]],
  ['relocation',['Relocation',['../db/dfb/structllvm_1_1ELFYAML_1_1Relocation.html',1,'llvm::ELFYAML']]],
  ['relocation_5finfo',['relocation_info',['../de/de3/structllvm_1_1MachO_1_1relocation__info.html',1,'llvm::MachO']]],
  ['relocationentry',['RelocationEntry',['../db/d75/classllvm_1_1RelocationEntry.html',1,'llvm']]],
  ['relocationref',['RelocationRef',['../dd/d56/classllvm_1_1object_1_1RelocationRef.html',1,'llvm::object']]],
  ['relocationsection',['RelocationSection',['../d8/d25/structllvm_1_1ELFYAML_1_1RelocationSection.html',1,'llvm::ELFYAML']]],
  ['relocationvalueref',['RelocationValueRef',['../d3/db4/classllvm_1_1RelocationValueRef.html',1,'llvm']]],
  ['relocs_5fcoff_5farm',['Relocs_Coff_ARM',['../dc/d56/classrelocs_1_1Relocs__Coff__ARM.html',1,'relocs']]],
  ['relocs_5fcoff_5fi386',['Relocs_Coff_i386',['../df/d81/classrelocs_1_1Relocs__Coff__i386.html',1,'relocs']]],
  ['relocs_5fcoff_5fx86_5f64',['Relocs_Coff_X86_64',['../dd/d08/classrelocs_1_1Relocs__Coff__X86__64.html',1,'relocs']]],
  ['relocs_5felf_5faarch64',['Relocs_Elf_AArch64',['../db/d9d/classrelocs_1_1Relocs__Elf__AArch64.html',1,'relocs']]],
  ['relocs_5felf_5farm',['Relocs_Elf_ARM',['../da/de0/classrelocs_1_1Relocs__Elf__ARM.html',1,'relocs']]],
  ['relocs_5felf_5fhexagon',['Relocs_Elf_Hexagon',['../d3/dc3/classrelocs_1_1Relocs__Elf__Hexagon.html',1,'relocs']]],
  ['relocs_5felf_5fi386',['Relocs_Elf_i386',['../dc/d5c/classrelocs_1_1Relocs__Elf__i386.html',1,'relocs']]],
  ['relocs_5felf_5fmips',['Relocs_Elf_Mips',['../df/d79/classrelocs_1_1Relocs__Elf__Mips.html',1,'relocs']]],
  ['relocs_5felf_5fppc32',['Relocs_Elf_PPC32',['../d5/d33/classrelocs_1_1Relocs__Elf__PPC32.html',1,'relocs']]],
  ['relocs_5felf_5fppc64',['Relocs_Elf_PPC64',['../d6/d69/classrelocs_1_1Relocs__Elf__PPC64.html',1,'relocs']]],
  ['relocs_5felf_5fx86_5f64',['Relocs_Elf_X86_64',['../d9/d93/classrelocs_1_1Relocs__Elf__X86__64.html',1,'relocs']]],
  ['relocs_5fmacho_5farm',['Relocs_Macho_ARM',['../dd/d01/classrelocs_1_1Relocs__Macho__ARM.html',1,'relocs']]],
  ['relocs_5fmacho_5fi386',['Relocs_Macho_i386',['../dc/d98/classrelocs_1_1Relocs__Macho__i386.html',1,'relocs']]],
  ['relocs_5fmacho_5fppc',['Relocs_Macho_PPC',['../d0/de8/classrelocs_1_1Relocs__Macho__PPC.html',1,'relocs']]],
  ['relocs_5fmacho_5fx86_5f64',['Relocs_Macho_X86_64',['../d5/d91/classrelocs_1_1Relocs__Macho__X86__64.html',1,'relocs']]],
  ['reloctoapply',['RelocToApply',['../d4/de3/structllvm_1_1object_1_1RelocToApply.html',1,'llvm::object']]],
  ['relocvisitor',['RelocVisitor',['../d8/dee/classllvm_1_1object_1_1RelocVisitor.html',1,'llvm::object']]],
  ['remat',['Remat',['../dc/daf/structllvm_1_1LiveRangeEdit_1_1Remat.html',1,'llvm::LiveRangeEdit']]],
  ['remotememorymanager',['RemoteMemoryManager',['../df/db2/classllvm_1_1RemoteMemoryManager.html',1,'llvm']]],
  ['remotetarget',['RemoteTarget',['../d3/d26/classllvm_1_1RemoteTarget.html',1,'llvm']]],
  ['remotetargetexternal',['RemoteTargetExternal',['../d8/da1/classllvm_1_1RemoteTargetExternal.html',1,'llvm']]],
  ['removeconst',['RemoveConst',['../de/d54/structtesting_1_1internal_1_1RemoveConst.html',1,'testing::internal']]],
  ['removeconst_3c_20const_20t_20_3e',['RemoveConst&lt; const T &gt;',['../d4/de8/structtesting_1_1internal_1_1RemoveConst_3_01const_01T_01_4.html',1,'testing::internal']]],
  ['removereference',['RemoveReference',['../d6/da7/structtesting_1_1internal_1_1RemoveReference.html',1,'testing::internal']]],
  ['removereference_3c_20t_20_26_20_3e',['RemoveReference&lt; T &amp; &gt;',['../d1/d78/structtesting_1_1internal_1_1RemoveReference_3_01T_01_6_01_4.html',1,'testing::internal']]],
  ['rerr',['rerr',['../df/d27/structrerr.html',1,'']]],
  ['resource_5fsort',['resource_sort',['../d6/d56/structllvm_1_1resource__sort.html',1,'llvm']]],
  ['resourceestimator',['ResourceEstimator',['../da/dfe/classlegup_1_1ResourceEstimator.html',1,'legup']]],
  ['resourcepriorityqueue',['ResourcePriorityQueue',['../d5/d77/classllvm_1_1ResourcePriorityQueue.html',1,'llvm']]],
  ['result',['Result',['../d3/d29/classllvm_1_1FunctionAnalysisManagerModuleProxy_1_1Result.html',1,'llvm::FunctionAnalysisManagerModuleProxy']]],
  ['result',['Result',['../dd/da6/classlit_1_1Test_1_1Result.html',1,'lit::Test']]],
  ['result',['Result',['../d0/d32/classllvm_1_1ModuleAnalysisManagerCGSCCProxy_1_1Result.html',1,'llvm::ModuleAnalysisManagerCGSCCProxy']]],
  ['result',['Result',['../d1/d5d/classllvm_1_1CGSCCAnalysisManagerFunctionProxy_1_1Result.html',1,'llvm::CGSCCAnalysisManagerFunctionProxy']]],
  ['result',['Result',['../d4/db8/classllvm_1_1CGSCCAnalysisManagerModuleProxy_1_1Result.html',1,'llvm::CGSCCAnalysisManagerModuleProxy']]],
  ['result',['Result',['../d0/dd1/classllvm_1_1ModuleAnalysisManagerFunctionProxy_1_1Result.html',1,'llvm::ModuleAnalysisManagerFunctionProxy']]],
  ['result',['Result',['../d1/dfb/classllvm_1_1FunctionAnalysisManagerCGSCCProxy_1_1Result.html',1,'llvm::FunctionAnalysisManagerCGSCCProxy']]],
  ['resultcode',['ResultCode',['../da/d8c/classlit_1_1Test_1_1ResultCode.html',1,'lit::Test']]],
  ['resulthasinvalidatemethod',['ResultHasInvalidateMethod',['../d8/dbc/classllvm_1_1detail_1_1ResultHasInvalidateMethod.html',1,'llvm::detail']]],
  ['resultoperand',['ResultOperand',['../d5/dfb/structllvm_1_1CodeGenInstAlias_1_1ResultOperand.html',1,'llvm::CodeGenInstAlias']]],
  ['resumeinst',['ResumeInst',['../d2/d67/classllvm_1_1ResumeInst.html',1,'llvm']]],
  ['returninst',['ReturnInst',['../d9/d12/classllvm_1_1ReturnInst.html',1,'llvm']]],
  ['reversepostordertraversal',['ReversePostOrderTraversal',['../db/d75/classllvm_1_1ReversePostOrderTraversal.html',1,'llvm']]],
  ['rgpassmanager',['RGPassManager',['../d5/d9e/classllvm_1_1RGPassManager.html',1,'llvm']]],
  ['ringentry',['RingEntry',['../d7/d65/structllvm_1_1ARM_1_1EHABI_1_1OpcodeDecoder_1_1RingEntry.html',1,'llvm::ARM::EHABI::OpcodeDecoder']]],
  ['ringentry',['RingEntry',['../d5/d36/structllvm_1_1ARM_1_1WinEH_1_1Decoder_1_1RingEntry.html',1,'llvm::ARM::WinEH::Decoder']]],
  ['rnsucciterator',['RNSuccIterator',['../dd/df0/classllvm_1_1RNSuccIterator.html',1,'llvm']]],
  ['rnsucciterator_3c_20flatit_3c_20nodetype_20_3e_2c_20blockt_2c_20regiont_20_3e',['RNSuccIterator&lt; FlatIt&lt; NodeType &gt;, BlockT, RegionT &gt;',['../d0/d97/classllvm_1_1RNSuccIterator_3_01FlatIt_3_01NodeType_01_4_00_01BlockT_00_01RegionT_01_4.html',1,'llvm']]],
  ['rootbranchdata',['RootBranchData',['../de/d33/structllvm_1_1IntervalMap_1_1RootBranchData.html',1,'llvm::IntervalMap']]],
  ['rootdata',['RootData',['../db/d64/structllvm_1_1SchedDFSImpl_1_1RootData.html',1,'llvm::SchedDFSImpl']]],
  ['rounduptopoweroftwo',['RoundUpToPowerOfTwo',['../df/d38/structllvm_1_1RoundUpToPowerOfTwo.html',1,'llvm']]],
  ['rounduptopoweroftwoh',['RoundUpToPowerOfTwoH',['../df/de9/structllvm_1_1RoundUpToPowerOfTwoH.html',1,'llvm']]],
  ['rounduptopoweroftwoh_3c_20n_2c_20false_20_3e',['RoundUpToPowerOfTwoH&lt; N, false &gt;',['../df/d5d/structllvm_1_1RoundUpToPowerOfTwoH_3_01N_00_01false_01_4.html',1,'llvm']]],
  ['routines_5fcommand',['routines_command',['../d3/d54/structllvm_1_1MachO_1_1routines__command.html',1,'llvm::MachO']]],
  ['routines_5fcommand_5f64',['routines_command_64',['../dd/d2d/structllvm_1_1MachO_1_1routines__command__64.html',1,'llvm::MachO']]],
  ['row',['Row',['../db/d79/structllvm_1_1DWARFDebugLine_1_1Row.html',1,'llvm::DWARFDebugLine']]],
  ['rpath_5fcommand',['rpath_command',['../d3/d3f/structllvm_1_1MachO_1_1rpath__command.html',1,'llvm::MachO']]],
  ['rpcchannel',['RPCChannel',['../d6/dd5/classllvm_1_1RPCChannel.html',1,'llvm']]],
  ['rtdyldmemorymanager',['RTDyldMemoryManager',['../d9/d41/classllvm_1_1RTDyldMemoryManager.html',1,'llvm']]],
  ['rtlconst',['RTLConst',['../db/d8f/classlegup_1_1RTLConst.html',1,'legup']]],
  ['rtldebugport',['RTLDebugPort',['../dd/ddf/classlegup_1_1RTLDebugPort.html',1,'legup']]],
  ['rtlmodule',['RTLModule',['../da/d6d/classlegup_1_1RTLModule.html',1,'legup']]],
  ['rtlmoduleinstance',['RTLModuleInstance',['../d1/d8f/classlegup_1_1RTLModuleInstance.html',1,'legup']]],
  ['rtlop',['RTLOp',['../db/d50/classlegup_1_1RTLOp.html',1,'legup']]],
  ['rtlsignal',['RTLSignal',['../d7/dc3/classlegup_1_1RTLSignal.html',1,'legup']]],
  ['rtlwidth',['RTLWidth',['../d4/d39/classlegup_1_1RTLWidth.html',1,'legup']]],
  ['run',['Run',['../d0/d26/classlit_1_1run_1_1Run.html',1,'lit::run']]],
  ['runtimedyld',['RuntimeDyld',['../d7/df8/classllvm_1_1RuntimeDyld.html',1,'llvm']]],
  ['runtimedyldchecker',['RuntimeDyldChecker',['../d1/def/classllvm_1_1RuntimeDyldChecker.html',1,'llvm']]],
  ['runtimedyldcheckerexpreval',['RuntimeDyldCheckerExprEval',['../d6/d0c/classllvm_1_1RuntimeDyldCheckerExprEval.html',1,'llvm']]],
  ['runtimedyldelf',['RuntimeDyldELF',['../d7/d45/classllvm_1_1RuntimeDyldELF.html',1,'llvm']]],
  ['runtimedyldimpl',['RuntimeDyldImpl',['../da/d7f/classllvm_1_1RuntimeDyldImpl.html',1,'llvm']]],
  ['runtimedyldmacho',['RuntimeDyldMachO',['../d1/d39/classllvm_1_1RuntimeDyldMachO.html',1,'llvm']]],
  ['runtimedyldmachoaarch64',['RuntimeDyldMachOAArch64',['../d1/dab/classllvm_1_1RuntimeDyldMachOAArch64.html',1,'llvm']]],
  ['runtimedyldmachoarm',['RuntimeDyldMachOARM',['../d5/d32/classllvm_1_1RuntimeDyldMachOARM.html',1,'llvm']]],
  ['runtimedyldmachocrtpbase',['RuntimeDyldMachOCRTPBase',['../d7/dd6/classllvm_1_1RuntimeDyldMachOCRTPBase.html',1,'llvm']]],
  ['runtimedyldmachocrtpbase_3c_20runtimedyldmachoaarch64_20_3e',['RuntimeDyldMachOCRTPBase&lt; RuntimeDyldMachOAArch64 &gt;',['../d7/dd6/classllvm_1_1RuntimeDyldMachOCRTPBase.html',1,'llvm']]],
  ['runtimedyldmachocrtpbase_3c_20runtimedyldmachoarm_20_3e',['RuntimeDyldMachOCRTPBase&lt; RuntimeDyldMachOARM &gt;',['../d7/dd6/classllvm_1_1RuntimeDyldMachOCRTPBase.html',1,'llvm']]],
  ['runtimedyldmachocrtpbase_3c_20runtimedyldmachoi386_20_3e',['RuntimeDyldMachOCRTPBase&lt; RuntimeDyldMachOI386 &gt;',['../d7/dd6/classllvm_1_1RuntimeDyldMachOCRTPBase.html',1,'llvm']]],
  ['runtimedyldmachocrtpbase_3c_20runtimedyldmachox86_5f64_20_3e',['RuntimeDyldMachOCRTPBase&lt; RuntimeDyldMachOX86_64 &gt;',['../d7/dd6/classllvm_1_1RuntimeDyldMachOCRTPBase.html',1,'llvm']]],
  ['runtimedyldmachoi386',['RuntimeDyldMachOI386',['../db/dd0/classllvm_1_1RuntimeDyldMachOI386.html',1,'llvm']]],
  ['runtimedyldmachox86_5f64',['RuntimeDyldMachOX86_64',['../d0/dcf/classllvm_1_1RuntimeDyldMachOX86__64.html',1,'llvm']]],
  ['runtimefunction',['RuntimeFunction',['../d2/d30/classllvm_1_1ARM_1_1WinEH_1_1RuntimeFunction.html',1,'llvm::ARM::WinEH']]],
  ['runtimefunction',['RuntimeFunction',['../db/d2b/structllvm_1_1Win64EH_1_1RuntimeFunction.html',1,'llvm::Win64EH']]],
  ['rwmuteximpl',['RWMutexImpl',['../d9/d8a/classllvm_1_1sys_1_1RWMutexImpl.html',1,'llvm::sys']]]
];
