var searchData=
[
  ['factory',['Factory',['../d4/d00/classllvm_1_1ImmutableMap_1_1Factory.html',1,'llvm::ImmutableMap']]],
  ['factory',['Factory',['../de/d73/classllvm_1_1ImmutableSet_1_1Factory.html',1,'llvm::ImmutableSet']]],
  ['fallback',['Fallback',['../d1/da7/structllvm_1_1yaml_1_1has__FlowTraits_3_01T_00_01true_01_4_1_1Fallback.html',1,'llvm::yaml::has_FlowTraits&lt; T, true &gt;']]],
  ['fastfoldingsetnode',['FastFoldingSetNode',['../d1/dc6/classllvm_1_1FastFoldingSetNode.html',1,'llvm']]],
  ['fastisel',['FastISel',['../d1/def/classllvm_1_1FastISel.html',1,'llvm']]],
  ['fastmathflagguard',['FastMathFlagGuard',['../d8/ddb/classllvm_1_1IRBuilderBase_1_1FastMathFlagGuard.html',1,'llvm::IRBuilderBase']]],
  ['fastmathflags',['FastMathFlags',['../d0/d27/classllvm_1_1FastMathFlags.html',1,'llvm']]],
  ['fat_5farch',['fat_arch',['../d8/dc9/structllvm_1_1MachO_1_1fat__arch.html',1,'llvm::MachO']]],
  ['fat_5fheader',['fat_header',['../d3/d09/structllvm_1_1MachO_1_1fat__header.html',1,'llvm::MachO']]],
  ['fcmpinst',['FCmpInst',['../d9/ddc/classllvm_1_1FCmpInst.html',1,'llvm']]],
  ['feasiblequeue',['FeasibleQueue',['../de/d22/classlegup_1_1FeasibleQueue.html',1,'legup']]],
  ['fenceinst',['FenceInst',['../d0/dfe/classllvm_1_1FenceInst.html',1,'llvm']]],
  ['fieldinit',['FieldInit',['../d8/def/classllvm_1_1FieldInit.html',1,'llvm']]],
  ['file_5fmagic',['file_magic',['../dc/d14/structllvm_1_1sys_1_1fs_1_1file__magic.html',1,'llvm::sys::fs']]],
  ['file_5fstatus',['file_status',['../d1/d87/classllvm_1_1sys_1_1fs_1_1file__status.html',1,'llvm::sys::fs']]],
  ['filebasedtest',['FileBasedTest',['../d1/dcc/classlit_1_1formats_1_1base_1_1FileBasedTest.html',1,'lit::formats::base']]],
  ['filehandletraits',['FileHandleTraits',['../d4/d0a/structFileHandleTraits.html',1,'']]],
  ['fileheader',['FileHeader',['../df/da2/structllvm_1_1ELFYAML_1_1FileHeader.html',1,'llvm::ELFYAML']]],
  ['fileinfo',['FileInfo',['../d8/de2/classllvm_1_1FileInfo.html',1,'llvm']]],
  ['filenamecache',['FilenameCache',['../dd/d9b/classllvm_1_1jitprofiling_1_1FilenameCache.html',1,'llvm::jitprofiling']]],
  ['filenameentry',['FileNameEntry',['../dc/dc2/structllvm_1_1DWARFDebugLine_1_1FileNameEntry.html',1,'llvm::DWARFDebugLine']]],
  ['filenameregistryty',['FileNameRegistryTy',['../d8/dd5/structllvm_1_1WinCodeViewLineTables_1_1FileNameRegistryTy.html',1,'llvm::WinCodeViewLineTables']]],
  ['fileoutputbuffer',['FileOutputBuffer',['../d2/df0/classllvm_1_1FileOutputBuffer.html',1,'llvm']]],
  ['filepath',['FilePath',['../de/dea/classtesting_1_1internal_1_1FilePath.html',1,'testing::internal']]],
  ['fileremover',['FileRemover',['../d1/d6f/classllvm_1_1FileRemover.html',1,'llvm']]],
  ['filteredpassnameparser',['FilteredPassNameParser',['../d2/dde/classllvm_1_1FilteredPassNameParser.html',1,'llvm']]],
  ['findelementarycycles',['FindElementaryCycles',['../d6/dee/classlegup_1_1FindElementaryCycles.html',1,'legup']]],
  ['findhandletraits',['FindHandleTraits',['../d8/dd0/structFindHandleTraits.html',1,'']]],
  ['findusedtypes',['FindUsedTypes',['../d3/d27/classllvm_1_1FindUsedTypes.html',1,'llvm']]],
  ['finitestatemachine',['FiniteStateMachine',['../d6/d88/classlegup_1_1FiniteStateMachine.html',1,'legup']]],
  ['fixedblockinfo',['FixedBlockInfo',['../df/d1b/structllvm_1_1MachineTraceMetrics_1_1FixedBlockInfo.html',1,'llvm::MachineTraceMetrics']]],
  ['fixednumoperandtraits',['FixedNumOperandTraits',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20atomiccmpxchginst_2c_203_20_3e',['FixedNumOperandTraits&lt; AtomicCmpXchgInst, 3 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20atomicrmwinst_2c_202_20_3e',['FixedNumOperandTraits&lt; AtomicRMWInst, 2 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20binaryconstantexpr_2c_202_20_3e',['FixedNumOperandTraits&lt; BinaryConstantExpr, 2 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20binaryoperator_2c_202_20_3e',['FixedNumOperandTraits&lt; BinaryOperator, 2 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20blockaddress_2c_202_20_3e',['FixedNumOperandTraits&lt; BlockAddress, 2 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20cmpinst_2c_202_20_3e',['FixedNumOperandTraits&lt; CmpInst, 2 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20compareconstantexpr_2c_202_20_3e',['FixedNumOperandTraits&lt; CompareConstantExpr, 2 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20constantplaceholder_2c_201_20_3e',['FixedNumOperandTraits&lt; ConstantPlaceHolder, 1 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20extractelementconstantexpr_2c_202_20_3e',['FixedNumOperandTraits&lt; ExtractElementConstantExpr, 2 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20extractelementinst_2c_202_20_3e',['FixedNumOperandTraits&lt; ExtractElementInst, 2 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20extractvalueconstantexpr_2c_201_20_3e',['FixedNumOperandTraits&lt; ExtractValueConstantExpr, 1 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20globalalias_2c_201_20_3e',['FixedNumOperandTraits&lt; GlobalAlias, 1 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20globalvariable_2c_201_20_3e',['FixedNumOperandTraits&lt; GlobalVariable, 1 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20insertelementconstantexpr_2c_203_20_3e',['FixedNumOperandTraits&lt; InsertElementConstantExpr, 3 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20insertelementinst_2c_203_20_3e',['FixedNumOperandTraits&lt; InsertElementInst, 3 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20insertvalueconstantexpr_2c_202_20_3e',['FixedNumOperandTraits&lt; InsertValueConstantExpr, 2 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20insertvalueinst_2c_202_20_3e',['FixedNumOperandTraits&lt; InsertValueInst, 2 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20resumeinst_2c_201_20_3e',['FixedNumOperandTraits&lt; ResumeInst, 1 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20selectconstantexpr_2c_203_20_3e',['FixedNumOperandTraits&lt; SelectConstantExpr, 3 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20selectinst_2c_203_20_3e',['FixedNumOperandTraits&lt; SelectInst, 3 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20shufflevectorconstantexpr_2c_203_20_3e',['FixedNumOperandTraits&lt; ShuffleVectorConstantExpr, 3 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20shufflevectorinst_2c_203_20_3e',['FixedNumOperandTraits&lt; ShuffleVectorInst, 3 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20storeinst_2c_202_20_3e',['FixedNumOperandTraits&lt; StoreInst, 2 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20unaryconstantexpr_2c_201_20_3e',['FixedNumOperandTraits&lt; UnaryConstantExpr, 1 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20unaryinstruction_2c_201_20_3e',['FixedNumOperandTraits&lt; UnaryInstruction, 1 &gt;',['../d8/d9c/structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixedstackpseudosourcevalue',['FixedStackPseudoSourceValue',['../dd/dfa/classllvm_1_1FixedStackPseudoSourceValue.html',1,'llvm']]],
  ['flagsmap',['FlagsMap',['../db/d48/structFlagsMap.html',1,'']]],
  ['flatit',['FlatIt',['../d3/d68/classllvm_1_1FlatIt.html',1,'llvm']]],
  ['floatingpoint',['FloatingPoint',['../dd/d0f/classtesting_1_1internal_1_1FloatingPoint.html',1,'testing::internal']]],
  ['floatingpointunion',['FloatingPointUnion',['../d6/dd2/uniontesting_1_1internal_1_1FloatingPoint_1_1FloatingPointUnion.html',1,'testing::internal::FloatingPoint']]],
  ['fltsemantics',['fltSemantics',['../dc/d5a/structllvm_1_1fltSemantics.html',1,'llvm']]],
  ['fneg_5fmatch',['fneg_match',['../dd/d5e/structllvm_1_1PatternMatch_1_1fneg__match.html',1,'llvm::PatternMatch']]],
  ['foldingset',['FoldingSet',['../d3/d2a/classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20listty_20_3e',['FoldingSet&lt; ListTy &gt;',['../d3/d2a/classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20llvm_3a_3aattributeimpl_20_3e',['FoldingSet&lt; llvm::AttributeImpl &gt;',['../d3/d2a/classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20llvm_3a_3aattributesetimpl_20_3e',['FoldingSet&lt; llvm::AttributeSetImpl &gt;',['../d3/d2a/classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20llvm_3a_3aattributesetnode_20_3e',['FoldingSet&lt; llvm::AttributeSetNode &gt;',['../d3/d2a/classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20llvm_3a_3adieabbrev_20_3e',['FoldingSet&lt; llvm::DIEAbbrev &gt;',['../d3/d2a/classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20llvm_3a_3amdnode_20_3e',['FoldingSet&lt; llvm::MDNode &gt;',['../d3/d2a/classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20llvm_3a_3ascev_20_3e',['FoldingSet&lt; llvm::SCEV &gt;',['../d3/d2a/classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20llvm_3a_3asdnode_20_3e',['FoldingSet&lt; llvm::SDNode &gt;',['../d3/d2a/classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20llvm_3a_3asdvtlistnode_20_3e',['FoldingSet&lt; llvm::SDVTListNode &gt;',['../d3/d2a/classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingsetbucketiterator',['FoldingSetBucketIterator',['../da/d1b/classllvm_1_1FoldingSetBucketIterator.html',1,'llvm']]],
  ['foldingsetbucketiteratorimpl',['FoldingSetBucketIteratorImpl',['../d4/dc5/classllvm_1_1FoldingSetBucketIteratorImpl.html',1,'llvm']]],
  ['foldingsetimpl',['FoldingSetImpl',['../d1/ddd/classllvm_1_1FoldingSetImpl.html',1,'llvm']]],
  ['foldingsetiterator',['FoldingSetIterator',['../d1/dc9/classllvm_1_1FoldingSetIterator.html',1,'llvm']]],
  ['foldingsetiteratorimpl',['FoldingSetIteratorImpl',['../d2/d9d/classllvm_1_1FoldingSetIteratorImpl.html',1,'llvm']]],
  ['foldingsetnodeid',['FoldingSetNodeID',['../db/dd3/classllvm_1_1FoldingSetNodeID.html',1,'llvm']]],
  ['foldingsetnodeidref',['FoldingSetNodeIDRef',['../d4/d57/classllvm_1_1FoldingSetNodeIDRef.html',1,'llvm']]],
  ['foldingsetnodewrapper',['FoldingSetNodeWrapper',['../d4/d6a/classllvm_1_1FoldingSetNodeWrapper.html',1,'llvm']]],
  ['foldingsettrait',['FoldingSetTrait',['../db/df8/structllvm_1_1FoldingSetTrait.html',1,'llvm']]],
  ['foldingsettrait_3c_20mdnode_20_3e',['FoldingSetTrait&lt; MDNode &gt;',['../d0/d51/structllvm_1_1FoldingSetTrait_3_01MDNode_01_4.html',1,'llvm']]],
  ['foldingsettrait_3c_20scev_20_3e',['FoldingSetTrait&lt; SCEV &gt;',['../df/d13/structllvm_1_1FoldingSetTrait_3_01SCEV_01_4.html',1,'llvm']]],
  ['foldingsettrait_3c_20sdvtlistnode_20_3e',['FoldingSetTrait&lt; SDVTListNode &gt;',['../d6/d51/structllvm_1_1FoldingSetTrait_3_01SDVTListNode_01_4.html',1,'llvm']]],
  ['foldingsettrait_3c_20std_3a_3apair_3c_20t1_2c_20t2_20_3e_20_3e',['FoldingSetTrait&lt; std::pair&lt; T1, T2 &gt; &gt;',['../d0/d17/structllvm_1_1FoldingSetTrait_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html',1,'llvm']]],
  ['foldingsettrait_3c_20t_20_2a_20_3e',['FoldingSetTrait&lt; T * &gt;',['../d2/d61/structllvm_1_1FoldingSetTrait_3_01T_01_5_01_4.html',1,'llvm']]],
  ['foldingsetvector',['FoldingSetVector',['../dd/df4/classllvm_1_1FoldingSetVector.html',1,'llvm']]],
  ['foldingsetvectoriterator',['FoldingSetVectorIterator',['../df/dff/classllvm_1_1FoldingSetVectorIterator.html',1,'llvm']]],
  ['foo',['foo',['../d3/dad/structfoo.html',1,'']]],
  ['foo',['foo',['../d1/dfa/structpr14763_1_1foo.html',1,'pr14763']]],
  ['foo',['foo',['../dc/d0c/structllvm_1_1foo.html',1,'llvm']]],
  ['foobar',['FooBar',['../df/d5c/structFooBar.html',1,'']]],
  ['foobarmap',['FooBarMap',['../db/da5/structFooBarMap.html',1,'']]],
  ['foreachloop',['ForeachLoop',['../d4/d46/structllvm_1_1ForeachLoop.html',1,'llvm']]],
  ['forexprast',['ForExprAST',['../d1/d9f/classForExprAST.html',1,'']]],
  ['format_5fobject1',['format_object1',['../d4/dcb/classllvm_1_1format__object1.html',1,'llvm']]],
  ['format_5fobject2',['format_object2',['../d7/d3b/classllvm_1_1format__object2.html',1,'llvm']]],
  ['format_5fobject3',['format_object3',['../d2/d22/classllvm_1_1format__object3.html',1,'llvm']]],
  ['format_5fobject4',['format_object4',['../da/def/classllvm_1_1format__object4.html',1,'llvm']]],
  ['format_5fobject5',['format_object5',['../d4/dc8/classllvm_1_1format__object5.html',1,'llvm']]],
  ['format_5fobject6',['format_object6',['../d1/d42/classllvm_1_1format__object6.html',1,'llvm']]],
  ['format_5fobject_5fbase',['format_object_base',['../dc/dcf/classllvm_1_1format__object__base.html',1,'llvm']]],
  ['formatbranchinfo',['formatBranchInfo',['../dc/d10/structformatBranchInfo.html',1,'']]],
  ['formatted_5fraw_5fostream',['formatted_raw_ostream',['../de/d35/classllvm_1_1formatted__raw__ostream.html',1,'llvm']]],
  ['forwarddominancefrontierbase',['ForwardDominanceFrontierBase',['../de/dbd/classllvm_1_1ForwardDominanceFrontierBase.html',1,'llvm']]],
  ['forwarddominancefrontierbase_3c_20llvm_3a_3abasicblock_20_3e',['ForwardDominanceFrontierBase&lt; llvm::BasicBlock &gt;',['../de/dbd/classllvm_1_1ForwardDominanceFrontierBase.html',1,'llvm']]],
  ['forwarddominancefrontierbase_3c_20llvm_3a_3amachinebasicblock_20_3e',['ForwardDominanceFrontierBase&lt; llvm::MachineBasicBlock &gt;',['../de/dbd/classllvm_1_1ForwardDominanceFrontierBase.html',1,'llvm']]],
  ['fp128',['fp128',['../d1/df9/classllvm_1_1types_1_1fp128.html',1,'llvm::types']]],
  ['fpextinst',['FPExtInst',['../d5/d79/classllvm_1_1FPExtInst.html',1,'llvm']]],
  ['fpmathoperator',['FPMathOperator',['../d8/dcd/classllvm_1_1FPMathOperator.html',1,'llvm']]],
  ['fppassmanager',['FPPassManager',['../d4/d43/classllvm_1_1FPPassManager.html',1,'llvm']]],
  ['fptosiinst',['FPToSIInst',['../d4/d25/classllvm_1_1FPToSIInst.html',1,'llvm']]],
  ['fptouiinst',['FPToUIInst',['../d2/d0d/classllvm_1_1FPToUIInst.html',1,'llvm']]],
  ['fptruncinst',['FPTruncInst',['../df/d74/classllvm_1_1FPTruncInst.html',1,'llvm']]],
  ['frameentry',['FrameEntry',['../da/dee/classllvm_1_1FrameEntry.html',1,'llvm']]],
  ['frameindexsdnode',['FrameIndexSDNode',['../d5/db3/classllvm_1_1FrameIndexSDNode.html',1,'llvm']]],
  ['freelist',['FreeList',['../d3/d4c/structllvm_1_1ArrayRecycler_1_1FreeList.html',1,'llvm::ArrayRecycler']]],
  ['frequencydata',['FrequencyData',['../d2/d0a/structllvm_1_1BlockFrequencyInfoImplBase_1_1FrequencyData.html',1,'llvm::BlockFrequencyInfoImplBase']]],
  ['fulldependence',['FullDependence',['../df/de7/classllvm_1_1FullDependence.html',1,'llvm']]],
  ['funclist',['FuncList',['../df/da7/classlegup_1_1FuncList.html',1,'legup']]],
  ['funcnamesignature',['FuncNameSignature',['../d0/d66/structllvm_1_1Mips16HardFloatInfo_1_1FuncNameSignature.html',1,'llvm::Mips16HardFloatInfo']]],
  ['funcsignature',['FuncSignature',['../dd/d86/structllvm_1_1Mips16HardFloatInfo_1_1FuncSignature.html',1,'llvm::Mips16HardFloatInfo']]],
  ['function',['Function',['../d6/d3f/structllvm_1_1MCModuleYAML_1_1Function.html',1,'llvm::MCModuleYAML']]],
  ['function',['Function',['../de/d7c/classllvm_1_1Function.html',1,'llvm']]],
  ['function',['Function',['../d1/df2/classllvm_1_1core_1_1Function.html',1,'llvm::core']]],
  ['function_5fref',['function_ref',['../d8/d4d/classllvm_1_1function__ref.html',1,'llvm']]],
  ['function_5fref_3c_20ret_28_29_3e',['function_ref&lt; Ret()&gt;',['../d1/d07/classllvm_1_1function__ref_3_01Ret_07_08_4.html',1,'llvm']]],
  ['function_5fref_3c_20ret_28param1_29_3e',['function_ref&lt; Ret(Param1)&gt;',['../dd/dbc/classllvm_1_1function__ref_3_01Ret_07Param1_08_4.html',1,'llvm']]],
  ['function_5fref_3c_20ret_28param1_2c_20param2_29_3e',['function_ref&lt; Ret(Param1, Param2)&gt;',['../db/d57/classllvm_1_1function__ref_3_01Ret_07Param1_00_01Param2_08_4.html',1,'llvm']]],
  ['function_5fref_3c_20ret_28param1_2c_20param2_2c_20param3_29_3e',['function_ref&lt; Ret(Param1, Param2, Param3)&gt;',['../db/d72/classllvm_1_1function__ref_3_01Ret_07Param1_00_01Param2_00_01Param3_08_4.html',1,'llvm']]],
  ['functionanalysismanager',['FunctionAnalysisManager',['../da/d45/classllvm_1_1FunctionAnalysisManager.html',1,'llvm']]],
  ['functionanalysismanagercgsccproxy',['FunctionAnalysisManagerCGSCCProxy',['../dd/dda/classllvm_1_1FunctionAnalysisManagerCGSCCProxy.html',1,'llvm']]],
  ['functionanalysismanagermoduleproxy',['FunctionAnalysisManagerModuleProxy',['../d0/d46/classllvm_1_1FunctionAnalysisManagerModuleProxy.html',1,'llvm']]],
  ['functionast',['FunctionAST',['../dd/d9e/classFunctionAST.html',1,'']]],
  ['functioninfo',['FunctionInfo',['../dc/d8c/structllvm_1_1WinCodeViewLineTables_1_1FunctionInfo.html',1,'llvm::WinCodeViewLineTables']]],
  ['functionloweringinfo',['FunctionLoweringInfo',['../db/d40/classllvm_1_1FunctionLoweringInfo.html',1,'llvm']]],
  ['functionpass',['FunctionPass',['../d5/d43/classllvm_1_1FunctionPass.html',1,'llvm']]],
  ['functionpassmanager',['FunctionPassManager',['../d0/d17/classllvm_1_1legacy_1_1FunctionPassManager.html',1,'llvm::legacy']]],
  ['functionpassmanager',['FunctionPassManager',['../df/daa/classllvm_1_1FunctionPassManager.html',1,'llvm']]],
  ['functionpassmanagerimpl',['FunctionPassManagerImpl',['../d9/de1/classllvm_1_1legacy_1_1FunctionPassManagerImpl.html',1,'llvm::legacy']]],
  ['functionpassmodel',['FunctionPassModel',['../dc/d7b/structllvm_1_1FunctionPassManager_1_1FunctionPassModel.html',1,'llvm::FunctionPassManager']]],
  ['functionsortingwrapper',['FunctionSortingWrapper',['../dd/db7/classlegup_1_1FunctionSortingWrapper.html',1,'legup']]],
  ['functiontype',['FunctionType',['../d3/da8/classllvm_1_1FunctionType.html',1,'llvm']]],
  ['functiontypekeyinfo',['FunctionTypeKeyInfo',['../d3/d5e/structllvm_1_1FunctionTypeKeyInfo.html',1,'llvm']]],
  ['functionwithcallcount',['FunctionWithCallCount',['../d2/d14/structlegup_1_1FunctionWithCallCount.html',1,'legup']]],
  ['functionwithsignals',['FunctionWithSignals',['../df/dea/classlegup_1_1FunctionWithSignals.html',1,'legup']]],
  ['fvmfile_5fcommand',['fvmfile_command',['../d4/d13/structllvm_1_1MachO_1_1fvmfile__command.html',1,'llvm::MachO']]],
  ['fvmlib',['fvmlib',['../d0/d3a/structllvm_1_1MachO_1_1fvmlib.html',1,'llvm::MachO']]],
  ['fvmlib_5fcommand',['fvmlib_command',['../dc/d29/structllvm_1_1MachO_1_1fvmlib__command.html',1,'llvm::MachO']]]
];
