var searchData=
[
  ['backedgetakeninfo',['BackedgeTakenInfo',['../d3/d56/classllvm_1_1ScalarEvolution_1_1BackedgeTakenInfo.html',1,'llvm::ScalarEvolution']]],
  ['bar',['bar',['../d7/db3/structllvm_1_1bar.html',1,'llvm']]],
  ['bar',['bar',['../dc/dca/structbar.html',1,'']]],
  ['basehelper',['BaseHelper',['../d2/daf/classBaseHelper.html',1,'']]],
  ['baseindexoffset',['BaseIndexOffset',['../d9/dfe/structBaseIndexOffset.html',1,'']]],
  ['baselint',['BaseLint',['../dd/d56/classcommon__lint_1_1BaseLint.html',1,'common_lint']]],
  ['basic_5fcollection_5fiterator',['basic_collection_iterator',['../d9/de9/classllvm_1_1yaml_1_1basic__collection__iterator.html',1,'llvm::yaml']]],
  ['basic_5fparser',['basic_parser',['../d7/dde/classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20bool_20_3e',['basic_parser&lt; bool &gt;',['../d7/dde/classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20boolordefault_20_3e',['basic_parser&lt; boolOrDefault &gt;',['../d7/dde/classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20char_20_3e',['basic_parser&lt; char &gt;',['../d7/dde/classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20double_20_3e',['basic_parser&lt; double &gt;',['../d7/dde/classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20float_20_3e',['basic_parser&lt; float &gt;',['../d7/dde/classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20int_20_3e',['basic_parser&lt; int &gt;',['../d7/dde/classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20std_3a_3astring_20_3e',['basic_parser&lt; std::string &gt;',['../d7/dde/classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20unsigned_20_3e',['basic_parser&lt; unsigned &gt;',['../d7/dde/classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20unsigned_20long_20long_20_3e',['basic_parser&lt; unsigned long long &gt;',['../d7/dde/classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_5fimpl',['basic_parser_impl',['../da/dc8/classllvm_1_1cl_1_1basic__parser__impl.html',1,'llvm::cl']]],
  ['basicblock',['BasicBlock',['../d7/df9/classllvm_1_1core_1_1BasicBlock.html',1,'llvm::core']]],
  ['basicblock',['BasicBlock',['../d4/d4f/structllvm_1_1MCModuleYAML_1_1BasicBlock.html',1,'llvm::MCModuleYAML']]],
  ['basicblock',['BasicBlock',['../d1/da7/classllvm_1_1BasicBlock.html',1,'llvm']]],
  ['basicblockedge',['BasicBlockEdge',['../d5/de3/classllvm_1_1BasicBlockEdge.html',1,'llvm']]],
  ['basicblocklivenessinfo',['BasicBlockLivenessInfo',['../d2/da4/structlegup_1_1LiveVariableAnalysis_1_1BasicBlockLivenessInfo.html',1,'legup::LiveVariableAnalysis']]],
  ['basicblockpass',['BasicBlockPass',['../dd/daf/classllvm_1_1BasicBlockPass.html',1,'llvm']]],
  ['basicblocksdnode',['BasicBlockSDNode',['../df/dc0/classllvm_1_1BasicBlockSDNode.html',1,'llvm']]],
  ['basicsymbolref',['BasicSymbolRef',['../db/d94/classllvm_1_1object_1_1BasicSymbolRef.html',1,'llvm::object']]],
  ['bbinfo',['BBInfo',['../d4/d8c/classllvm_1_1SSAUpdaterImpl_1_1BBInfo.html',1,'llvm::SSAUpdaterImpl']]],
  ['bigtype',['BigType',['../d4/d21/structllvm_1_1detail_1_1PassRunAcceptsAnalysisManager_1_1BigType.html',1,'llvm::detail::PassRunAcceptsAnalysisManager']]],
  ['bigtype',['BigType',['../d0/d4b/structllvm_1_1detail_1_1ResultHasInvalidateMethod_1_1BigType.html',1,'llvm::detail::ResultHasInvalidateMethod']]],
  ['binary',['Binary',['../dd/df0/classllvm_1_1object_1_1Binary.html',1,'llvm::object']]],
  ['binary_5fle_5fimpl',['binary_le_impl',['../d9/d07/structbinary__le__impl.html',1,'']]],
  ['binaryconstantexpr',['BinaryConstantExpr',['../d2/df0/classllvm_1_1BinaryConstantExpr.html',1,'llvm']]],
  ['binaryexprast',['BinaryExprAST',['../da/d75/classBinaryExprAST.html',1,'']]],
  ['binaryholder',['BinaryHolder',['../d5/d72/structBinaryHolder.html',1,'']]],
  ['binaryop_5fmatch',['BinaryOp_match',['../d5/da6/structllvm_1_1PatternMatch_1_1BinaryOp__match.html',1,'llvm::PatternMatch']]],
  ['binaryoperator',['BinaryOperator',['../d0/d24/classllvm_1_1BinaryOperator.html',1,'llvm']]],
  ['binaryreader',['BinaryReader',['../df/d7f/classrelocs_1_1BinaryReader.html',1,'relocs']]],
  ['binaryref',['BinaryRef',['../d4/d14/classllvm_1_1yaml_1_1BinaryRef.html',1,'llvm::yaml']]],
  ['binarysdnode',['BinarySDNode',['../d4/d85/classllvm_1_1BinarySDNode.html',1,'llvm']]],
  ['binarywithflagssdnode',['BinaryWithFlagsSDNode',['../d2/db5/classllvm_1_1BinaryWithFlagsSDNode.html',1,'llvm']]],
  ['bind_5fconst_5fintval_5fty',['bind_const_intval_ty',['../db/d6e/structllvm_1_1PatternMatch_1_1bind__const__intval__ty.html',1,'llvm::PatternMatch']]],
  ['bind_5fty',['bind_ty',['../d9/d2f/structllvm_1_1PatternMatch_1_1bind__ty.html',1,'llvm::PatternMatch']]],
  ['binding',['Binding',['../d9/d1d/classlegup_1_1Binding.html',1,'legup']]],
  ['binop2_5fmatch',['BinOp2_match',['../dd/dbb/structllvm_1_1PatternMatch_1_1BinOp2__match.html',1,'llvm::PatternMatch']]],
  ['binopinit',['BinOpInit',['../dc/d82/classllvm_1_1BinOpInit.html',1,'llvm']]],
  ['bipartiteweightedmatchingbinding',['BipartiteWeightedMatchingBinding',['../d2/d18/classlegup_1_1BipartiteWeightedMatchingBinding.html',1,'legup']]],
  ['bitcastinst',['BitCastInst',['../df/d63/classllvm_1_1BitCastInst.html',1,'llvm']]],
  ['bitcodeabbrev',['BitCodeAbbrev',['../d8/dc4/classllvm_1_1BitCodeAbbrev.html',1,'llvm']]],
  ['bitcodeabbrevop',['BitCodeAbbrevOp',['../de/dc0/classllvm_1_1BitCodeAbbrevOp.html',1,'llvm']]],
  ['bitcodereader',['BitcodeReader',['../df/dab/classllvm_1_1BitcodeReader.html',1,'llvm']]],
  ['bitcodereadermdvaluelist',['BitcodeReaderMDValueList',['../dd/d8c/classllvm_1_1BitcodeReaderMDValueList.html',1,'llvm']]],
  ['bitcodereadervaluelist',['BitcodeReaderValueList',['../d8/d36/classllvm_1_1BitcodeReaderValueList.html',1,'llvm']]],
  ['bitcodewriterpass',['BitcodeWriterPass',['../d5/dd9/classllvm_1_1BitcodeWriterPass.html',1,'llvm']]],
  ['bitinit',['BitInit',['../d6/df1/classllvm_1_1BitInit.html',1,'llvm']]],
  ['bitrecty',['BitRecTy',['../de/da9/classllvm_1_1BitRecTy.html',1,'llvm']]],
  ['bits',['bits',['../d7/ddb/classllvm_1_1cl_1_1bits.html',1,'llvm::cl']]],
  ['bits_5fstorage',['bits_storage',['../d4/d53/classllvm_1_1cl_1_1bits__storage.html',1,'llvm::cl']]],
  ['bits_5fstorage_3c_20datatype_2c_20bool_20_3e',['bits_storage&lt; DataType, bool &gt;',['../da/d39/classllvm_1_1cl_1_1bits__storage_3_01DataType_00_01bool_01_4.html',1,'llvm::cl']]],
  ['bits_5fstorage_3c_20datatype_2c_20storage_20_3e',['bits_storage&lt; DataType, Storage &gt;',['../d4/d53/classllvm_1_1cl_1_1bits__storage.html',1,'llvm::cl']]],
  ['bitsinit',['BitsInit',['../df/dd4/classllvm_1_1BitsInit.html',1,'llvm']]],
  ['bitsrecty',['BitsRecTy',['../df/d01/classllvm_1_1BitsRecTy.html',1,'llvm']]],
  ['bitstreamcursor',['BitstreamCursor',['../df/da1/classllvm_1_1BitstreamCursor.html',1,'llvm']]],
  ['bitstreamentry',['BitstreamEntry',['../df/df5/structllvm_1_1BitstreamEntry.html',1,'llvm']]],
  ['bitstreamreader',['BitstreamReader',['../dc/df1/classllvm_1_1BitstreamReader.html',1,'llvm']]],
  ['bitstreamwriter',['BitstreamWriter',['../d8/db5/classllvm_1_1BitstreamWriter.html',1,'llvm']]],
  ['bittestblock',['BitTestBlock',['../d2/d98/structllvm_1_1SelectionDAGBuilder_1_1BitTestBlock.html',1,'llvm::SelectionDAGBuilder']]],
  ['bittestcase',['BitTestCase',['../da/daa/structllvm_1_1SelectionDAGBuilder_1_1BitTestCase.html',1,'llvm::SelectionDAGBuilder']]],
  ['bitvector',['BitVector',['../d4/d1f/classllvm_1_1BitVector.html',1,'llvm']]],
  ['bitvectoremitter',['BitVectorEmitter',['../d0/d2b/classBitVectorEmitter.html',1,'']]],
  ['block',['Block',['../d9/d1a/structllvm_1_1BitstreamCursor_1_1Block.html',1,'llvm::BitstreamCursor']]],
  ['block',['Block',['../dd/d74/structllvm_1_1BitstreamWriter_1_1Block.html',1,'llvm::BitstreamWriter']]],
  ['block_5fiterator_5fwrapper',['block_iterator_wrapper',['../d2/da3/classllvm_1_1RegionBase_1_1block__iterator__wrapper.html',1,'llvm::RegionBase']]],
  ['blockaddress',['BlockAddress',['../d2/d23/classllvm_1_1BlockAddress.html',1,'llvm']]],
  ['blockaddresssdnode',['BlockAddressSDNode',['../d9/d6c/classllvm_1_1BlockAddressSDNode.html',1,'llvm']]],
  ['blockconstraint',['BlockConstraint',['../d7/dc4/structllvm_1_1SpillPlacement_1_1BlockConstraint.html',1,'llvm::SpillPlacement']]],
  ['blockedgesadder',['BlockEdgesAdder',['../dd/d51/structllvm_1_1bfi__detail_1_1BlockEdgesAdder.html',1,'llvm::bfi_detail']]],
  ['blockfrequency',['BlockFrequency',['../d7/de9/classllvm_1_1BlockFrequency.html',1,'llvm']]],
  ['blockfrequencyinfo',['BlockFrequencyInfo',['../d2/d80/classllvm_1_1BlockFrequencyInfo.html',1,'llvm']]],
  ['blockfrequencyinfoimpl',['BlockFrequencyInfoImpl',['../dd/d87/classllvm_1_1BlockFrequencyInfoImpl.html',1,'llvm']]],
  ['blockfrequencyinfoimpl_3c_20bt_20_3e',['BlockFrequencyInfoImpl&lt; BT &gt;',['../dd/d87/classllvm_1_1BlockFrequencyInfoImpl.html',1,'llvm']]],
  ['blockfrequencyinfoimplbase',['BlockFrequencyInfoImplBase',['../d5/df2/classllvm_1_1BlockFrequencyInfoImplBase.html',1,'llvm']]],
  ['blockinfo',['BlockInfo',['../da/dd9/structllvm_1_1BitstreamReader_1_1BlockInfo.html',1,'llvm::BitstreamReader']]],
  ['blockinfo',['BlockInfo',['../d4/dbf/structllvm_1_1SplitAnalysis_1_1BlockInfo.html',1,'llvm::SplitAnalysis']]],
  ['blockinfo',['BlockInfo',['../de/d65/structllvm_1_1BitstreamWriter_1_1BlockInfo.html',1,'llvm::BitstreamWriter']]],
  ['blockinterference',['BlockInterference',['../d7/dbe/structllvm_1_1InterferenceCache_1_1BlockInterference.html',1,'llvm::InterferenceCache']]],
  ['blockmass',['BlockMass',['../da/d40/classllvm_1_1bfi__detail_1_1BlockMass.html',1,'llvm::bfi_detail']]],
  ['blocknode',['BlockNode',['../d0/d2b/structllvm_1_1BlockFrequencyInfoImplBase_1_1BlockNode.html',1,'llvm::BlockFrequencyInfoImplBase']]],
  ['bool_5fconstant',['bool_constant',['../d3/d75/structtesting_1_1internal_1_1bool__constant.html',1,'testing::internal']]],
  ['bool_5fconstant_3c_20implicitlyconvertible_3c_20const_20t_20_2a_2c_20const_20_3a_3aprotocolmessage_20_2a_20_3e_3a_3avalue_7c_7cimplicitlyconvertible_3c_20const_20t_20_2a_2c_20const_20_3a_3aproto2_3a_3amessage_20_2a_20_3e_3a_3avalue_20_3e',['bool_constant&lt; ImplicitlyConvertible&lt; const T *, const ::ProtocolMessage * &gt;::value||ImplicitlyConvertible&lt; const T *, const ::proto2::Message * &gt;::value &gt;',['../d3/d75/structtesting_1_1internal_1_1bool__constant.html',1,'testing::internal']]],
  ['boundinfo',['BoundInfo',['../df/dc2/structllvm_1_1DependenceAnalysis_1_1BoundInfo.html',1,'llvm::DependenceAnalysis']]],
  ['br_5fmatch',['br_match',['../df/d67/structllvm_1_1PatternMatch_1_1br__match.html',1,'llvm::PatternMatch']]],
  ['brainf',['BrainF',['../d3/d39/classBrainF.html',1,'']]],
  ['branch',['Branch',['../d6/d62/structllvm_1_1SystemZII_1_1Branch.html',1,'llvm::SystemZII']]],
  ['branchfolder',['BranchFolder',['../d0/deb/classllvm_1_1BranchFolder.html',1,'llvm']]],
  ['branchinst',['BranchInst',['../dc/de7/classllvm_1_1BranchInst.html',1,'llvm']]],
  ['branchnode',['BranchNode',['../de/d10/classllvm_1_1IntervalMapImpl_1_1BranchNode.html',1,'llvm::IntervalMapImpl']]],
  ['branchnode_3c_20keyt_2c_20valt_2c_20rootbranchcap_2c_20traits_20_3e',['BranchNode&lt; KeyT, ValT, RootBranchCap, Traits &gt;',['../de/d10/classllvm_1_1IntervalMapImpl_1_1BranchNode.html',1,'llvm::IntervalMapImpl']]],
  ['branchprobability',['BranchProbability',['../db/d3e/classllvm_1_1BranchProbability.html',1,'llvm']]],
  ['branchprobabilityinfo',['BranchProbabilityInfo',['../d1/d62/classllvm_1_1BranchProbabilityInfo.html',1,'llvm']]],
  ['brc_5fmatch',['brc_match',['../de/dd8/structllvm_1_1PatternMatch_1_1brc__match.html',1,'llvm::PatternMatch']]],
  ['bucket',['Bucket',['../d3/d11/classllvm_1_1OnDiskChainedHashTableGenerator_1_1Bucket.html',1,'llvm::OnDiskChainedHashTableGenerator']]],
  ['bugdriver',['BugDriver',['../d6/df0/classllvm_1_1BugDriver.html',1,'llvm']]],
  ['buildtoolcomponentinfo',['BuildToolComponentInfo',['../d2/d8b/classllvmbuild_1_1componentinfo_1_1BuildToolComponentInfo.html',1,'llvmbuild::componentinfo']]],
  ['buildvectorsdnode',['BuildVectorSDNode',['../df/d3a/classllvm_1_1BuildVectorSDNode.html',1,'llvm']]],
  ['builtintypes',['BuiltInTypes',['../d8/d8b/structBuiltInTypes.html',1,'']]],
  ['bumpptrallocatorimpl',['BumpPtrAllocatorImpl',['../da/db1/classllvm_1_1BumpPtrAllocatorImpl.html',1,'llvm']]],
  ['bundle_5fiterator',['bundle_iterator',['../de/db4/classllvm_1_1MachineBasicBlock_1_1bundle__iterator.html',1,'llvm::MachineBasicBlock']]],
  ['byref',['ByRef',['../d1/d1d/structstd_1_1tr1_1_1gtest__internal_1_1ByRef.html',1,'std::tr1::gtest_internal']]],
  ['byref_3c_20t_20_26_20_3e',['ByRef&lt; T &amp; &gt;',['../df/de2/structstd_1_1tr1_1_1gtest__internal_1_1ByRef_3_01T_01_6_01_4.html',1,'std::tr1::gtest_internal']]],
  ['bytestreamer',['ByteStreamer',['../dd/d68/classllvm_1_1ByteStreamer.html',1,'llvm']]],
  ['byvalarginfo',['ByValArgInfo',['../df/dc7/structllvm_1_1MipsTargetLowering_1_1ByValArgInfo.html',1,'llvm::MipsTargetLowering']]],
  ['byvalinfo',['ByValInfo',['../df/d19/structllvm_1_1CCState_1_1ByValInfo.html',1,'llvm::CCState']]]
];
