var searchData=
[
  ['vaarginst',['VAArgInst',['../dd/d60/classllvm_1_1VAArgInst.html',1,'llvm']]],
  ['vacopyinst',['VACopyInst',['../d3/d37/classllvm_1_1VACopyInst.html',1,'llvm']]],
  ['vaendinst',['VAEndInst',['../dd/d96/classllvm_1_1VAEndInst.html',1,'llvm']]],
  ['valid',['ValID',['../de/d9a/structllvm_1_1ValID.html',1,'llvm']]],
  ['validatedmappingtraits',['validatedMappingTraits',['../d6/d2e/structllvm_1_1yaml_1_1validatedMappingTraits.html',1,'llvm::yaml']]],
  ['value',['Value',['../d3/d35/structllvm_1_1DebugLocEntry_1_1Value.html',1,'llvm::DebugLocEntry']]],
  ['value',['Value',['../dd/d38/classllvm_1_1Value.html',1,'llvm']]],
  ['value',['Value',['../dd/d65/classllvm_1_1core_1_1Value.html',1,'llvm::core']]],
  ['value_5fdesc',['value_desc',['../d6/d39/structllvm_1_1cl_1_1value__desc.html',1,'llvm::cl']]],
  ['value_5fop_5fiterator',['value_op_iterator',['../d5/d2f/structllvm_1_1User_1_1value__op__iterator.html',1,'llvm::User']]],
  ['valueenumerator',['ValueEnumerator',['../d5/dc2/classllvm_1_1ValueEnumerator.html',1,'llvm']]],
  ['valuehandlebase',['ValueHandleBase',['../d9/dae/classllvm_1_1ValueHandleBase.html',1,'llvm']]],
  ['valuemap',['ValueMap',['../d0/d6f/classllvm_1_1ValueMap.html',1,'llvm']]],
  ['valuemap_3c_20basicblock_20_2a_2c_20basicblocklivenessinfo_20_2a_20_3e',['ValueMap&lt; BasicBlock *, BasicBlockLivenessInfo * &gt;',['../d0/d6f/classllvm_1_1ValueMap.html',1,'llvm']]],
  ['valuemap_3c_20const_20allocainst_20_2a_2c_20ssplayoutkind_20_3e',['ValueMap&lt; const AllocaInst *, SSPLayoutKind &gt;',['../d0/d6f/classllvm_1_1ValueMap.html',1,'llvm']]],
  ['valuemap_3c_20const_20basicblock_20_2a_2c_20void_20_2a_20_3e',['ValueMap&lt; const BasicBlock *, void * &gt;',['../d0/d6f/classllvm_1_1ValueMap.html',1,'llvm']]],
  ['valuemap_3c_20const_20globalvalue_20_2a_2c_20void_20_2a_2c_20addressmapconfig_20_3e',['ValueMap&lt; const GlobalValue *, void *, AddressMapConfig &gt;',['../d0/d6f/classllvm_1_1ValueMap.html',1,'llvm']]],
  ['valuemap_3c_20const_20llvm_3a_3aglobalvalue_20_2a_2c_20const_20llvm_3a_3amipscallentry_20_2a_20_3e',['ValueMap&lt; const llvm::GlobalValue *, const llvm::MipsCallEntry * &gt;',['../d0/d6f/classllvm_1_1ValueMap.html',1,'llvm']]],
  ['valuemap_3c_20value_20_2a_2c_20unsigned_20_3e',['ValueMap&lt; Value *, unsigned &gt;',['../d0/d6f/classllvm_1_1ValueMap.html',1,'llvm']]],
  ['valuemapcallbackvh',['ValueMapCallbackVH',['../d4/d50/classllvm_1_1ValueMapCallbackVH.html',1,'llvm']]],
  ['valuemapconfig',['ValueMapConfig',['../d5/d46/structllvm_1_1ValueMapConfig.html',1,'llvm']]],
  ['valuemapconfig_3c_20basicblock_20_2a_20_3e',['ValueMapConfig&lt; BasicBlock * &gt;',['../d5/d46/structllvm_1_1ValueMapConfig.html',1,'llvm']]],
  ['valuemapconfig_3c_20const_20allocainst_20_2a_20_3e',['ValueMapConfig&lt; const AllocaInst * &gt;',['../d5/d46/structllvm_1_1ValueMapConfig.html',1,'llvm']]],
  ['valuemapconfig_3c_20const_20basicblock_20_2a_20_3e',['ValueMapConfig&lt; const BasicBlock * &gt;',['../d5/d46/structllvm_1_1ValueMapConfig.html',1,'llvm']]],
  ['valuemapconfig_3c_20const_20globalvalue_20_2a_20_3e',['ValueMapConfig&lt; const GlobalValue * &gt;',['../d5/d46/structllvm_1_1ValueMapConfig.html',1,'llvm']]],
  ['valuemapconfig_3c_20const_20llvm_3a_3aglobalvalue_20_2a_20_3e',['ValueMapConfig&lt; const llvm::GlobalValue * &gt;',['../d5/d46/structllvm_1_1ValueMapConfig.html',1,'llvm']]],
  ['valuemapconfig_3c_20value_20_2a_20_3e',['ValueMapConfig&lt; Value * &gt;',['../d5/d46/structllvm_1_1ValueMapConfig.html',1,'llvm']]],
  ['valuemapconstiterator',['ValueMapConstIterator',['../d8/df3/classllvm_1_1ValueMapConstIterator.html',1,'llvm']]],
  ['valuemapiterator',['ValueMapIterator',['../da/d22/classllvm_1_1ValueMapIterator.html',1,'llvm']]],
  ['valuemaptyperemapper',['ValueMapTypeRemapper',['../d9/d89/classllvm_1_1ValueMapTypeRemapper.html',1,'llvm']]],
  ['valuematerializer',['ValueMaterializer',['../d8/db8/classllvm_1_1ValueMaterializer.html',1,'llvm']]],
  ['valuesclass',['ValuesClass',['../d5/d12/classllvm_1_1cl_1_1ValuesClass.html',1,'llvm::cl']]],
  ['valuesymboltable',['ValueSymbolTable',['../d5/d6f/classllvm_1_1ValueSymbolTable.html',1,'llvm']]],
  ['valuetype',['ValueType',['../da/dd7/structllvm_1_1DWARFFormValue_1_1ValueType.html',1,'llvm::DWARFFormValue']]],
  ['valuetypeactionimpl',['ValueTypeActionImpl',['../d8/d3f/classllvm_1_1TargetLoweringBase_1_1ValueTypeActionImpl.html',1,'llvm::TargetLoweringBase']]],
  ['valuetypeproxy',['ValueTypeProxy',['../dc/d1e/structllvm_1_1ValueMapConstIterator_1_1ValueTypeProxy.html',1,'llvm::ValueMapConstIterator']]],
  ['valuetypeproxy',['ValueTypeProxy',['../d2/d7f/structllvm_1_1ValueMapIterator_1_1ValueTypeProxy.html',1,'llvm::ValueMapIterator']]],
  ['varbitinit',['VarBitInit',['../dd/d19/classllvm_1_1VarBitInit.html',1,'llvm']]],
  ['varexprast',['VarExprAST',['../da/d63/classVarExprAST.html',1,'']]],
  ['variabledbginfo',['VariableDbgInfo',['../df/d7f/structllvm_1_1MachineModuleInfo_1_1VariableDbgInfo.html',1,'llvm::MachineModuleInfo']]],
  ['variableexprast',['VariableExprAST',['../d5/dd9/classVariableExprAST.html',1,'']]],
  ['variadicfunction',['VariadicFunction',['../d5/d6a/structllvm_1_1VariadicFunction.html',1,'llvm']]],
  ['variadicfunction1',['VariadicFunction1',['../db/d3c/structllvm_1_1VariadicFunction1.html',1,'llvm']]],
  ['variadicfunction2',['VariadicFunction2',['../d7/dbf/structllvm_1_1VariadicFunction2.html',1,'llvm']]],
  ['variadicfunction3',['VariadicFunction3',['../d2/d42/structllvm_1_1VariadicFunction3.html',1,'llvm']]],
  ['variadicoperandtraits',['VariadicOperandTraits',['../dc/d73/structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20branchinst_2c_201_20_3e',['VariadicOperandTraits&lt; BranchInst, 1 &gt;',['../dc/d73/structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20callinst_2c_201_20_3e',['VariadicOperandTraits&lt; CallInst, 1 &gt;',['../dc/d73/structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20constantarray_20_3e',['VariadicOperandTraits&lt; ConstantArray &gt;',['../dc/d73/structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20constantexpr_2c_201_20_3e',['VariadicOperandTraits&lt; ConstantExpr, 1 &gt;',['../dc/d73/structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20constantstruct_20_3e',['VariadicOperandTraits&lt; ConstantStruct &gt;',['../dc/d73/structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20constantvector_20_3e',['VariadicOperandTraits&lt; ConstantVector &gt;',['../dc/d73/structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20getelementptrconstantexpr_2c_201_20_3e',['VariadicOperandTraits&lt; GetElementPtrConstantExpr, 1 &gt;',['../dc/d73/structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20getelementptrinst_2c_201_20_3e',['VariadicOperandTraits&lt; GetElementPtrInst, 1 &gt;',['../dc/d73/structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20invokeinst_2c_203_20_3e',['VariadicOperandTraits&lt; InvokeInst, 3 &gt;',['../dc/d73/structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20returninst_20_3e',['VariadicOperandTraits&lt; ReturnInst &gt;',['../dc/d73/structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['varinfo',['VarInfo',['../df/d5f/structllvm_1_1LiveVariables_1_1VarInfo.html',1,'llvm::LiveVariables']]],
  ['varinit',['VarInit',['../d2/df0/classllvm_1_1VarInit.html',1,'llvm']]],
  ['varlistelementinit',['VarListElementInit',['../d2/d80/classllvm_1_1VarListElementInit.html',1,'llvm']]],
  ['vastartinst',['VAStartInst',['../d9/d93/classllvm_1_1VAStartInst.html',1,'llvm']]],
  ['vdup',['vdup',['../d1/da4/structvdup.html',1,'']]],
  ['vector',['Vector',['../d7/df4/classPBQP_1_1Vector.html',1,'PBQP']]],
  ['vectorcomparator',['VectorComparator',['../da/d6e/classPBQP_1_1VectorComparator.html',1,'PBQP']]],
  ['vectorizeconfig',['VectorizeConfig',['../d8/d8c/structllvm_1_1VectorizeConfig.html',1,'llvm']]],
  ['vectortype',['VectorType',['../d3/d45/classllvm_1_1VectorType.html',1,'llvm']]],
  ['verifierpass',['VerifierPass',['../dc/dff/classllvm_1_1VerifierPass.html',1,'llvm']]],
  ['verilogtargetmachine',['VerilogTargetMachine',['../d3/dde/structllvm_1_1VerilogTargetMachine.html',1,'llvm']]],
  ['verilogwriter',['VerilogWriter',['../db/df4/classlegup_1_1VerilogWriter.html',1,'legup']]],
  ['version_5fmin_5fcommand',['version_min_command',['../da/deb/structllvm_1_1MachO_1_1version__min__command.html',1,'llvm::MachO']]],
  ['versionmapentry',['VersionMapEntry',['../d6/d5c/classllvm_1_1object_1_1ELFFile_1_1VersionMapEntry.html',1,'llvm::object::ELFFile']]],
  ['versionmininfotype',['VersionMinInfoType',['../d7/dad/structllvm_1_1MCAssembler_1_1VersionMinInfoType.html',1,'llvm::MCAssembler']]],
  ['vext',['vext',['../dd/d78/structvext.html',1,'']]],
  ['virtreg2indexfunctor',['VirtReg2IndexFunctor',['../d7/d8b/structllvm_1_1VirtReg2IndexFunctor.html',1,'llvm']]],
  ['virtregauxinfo',['VirtRegAuxInfo',['../d7/dbb/classllvm_1_1VirtRegAuxInfo.html',1,'llvm']]],
  ['virtreginfo',['VirtRegInfo',['../db/ded/structllvm_1_1MachineOperandIteratorBase_1_1VirtRegInfo.html',1,'llvm::MachineOperandIteratorBase']]],
  ['virtregmap',['VirtRegMap',['../dd/db0/classllvm_1_1VirtRegMap.html',1,'llvm']]],
  ['visibility',['Visibility',['../db/d41/classllvm_1_1core_1_1Visibility.html',1,'llvm::core']]],
  ['vliwmachinescheduler',['VLIWMachineScheduler',['../d0/d00/classllvm_1_1VLIWMachineScheduler.html',1,'llvm']]],
  ['vliwpacketizerlist',['VLIWPacketizerList',['../dd/db5/classllvm_1_1VLIWPacketizerList.html',1,'llvm']]],
  ['vliwresourcemodel',['VLIWResourceModel',['../da/dfe/classllvm_1_1VLIWResourceModel.html',1,'llvm']]],
  ['vliwschedboundary',['VLIWSchedBoundary',['../de/d66/structllvm_1_1ConvergingVLIWScheduler_1_1VLIWSchedBoundary.html',1,'llvm::ConvergingVLIWScheduler']]],
  ['vninfo',['VNInfo',['../d9/dc4/classllvm_1_1VNInfo.html',1,'llvm']]],
  ['vreg2sunit',['VReg2SUnit',['../dc/d19/structllvm_1_1VReg2SUnit.html',1,'llvm']]],
  ['vrev',['vrev',['../da/d6d/structvrev.html',1,'']]],
  ['vtrnl',['vtrnl',['../d0/dbf/structvtrnl.html',1,'']]],
  ['vtrnr',['vtrnr',['../d1/d3a/structvtrnr.html',1,'']]],
  ['vtsdnode',['VTSDNode',['../d7/db6/classllvm_1_1VTSDNode.html',1,'llvm']]],
  ['vuzpl',['vuzpl',['../de/d26/structvuzpl.html',1,'']]],
  ['vuzpr',['vuzpr',['../d2/df3/structvuzpr.html',1,'']]],
  ['vzipl',['vzipl',['../dd/dec/structvzipl.html',1,'']]],
  ['vzipr',['vzipr',['../d8/d0f/structvzipr.html',1,'']]]
];
