var ConstantsContext_8h =
[
    [ "ConstantTraits", "dc/de5/structllvm_1_1ConstantTraits.html", null ],
    [ "UnaryConstantExpr", "d6/d46/classllvm_1_1UnaryConstantExpr.html", "d6/d46/classllvm_1_1UnaryConstantExpr" ],
    [ "BinaryConstantExpr", "d2/df0/classllvm_1_1BinaryConstantExpr.html", "d2/df0/classllvm_1_1BinaryConstantExpr" ],
    [ "SelectConstantExpr", "d5/d3f/classllvm_1_1SelectConstantExpr.html", "d5/d3f/classllvm_1_1SelectConstantExpr" ],
    [ "ExtractElementConstantExpr", "da/d07/classllvm_1_1ExtractElementConstantExpr.html", "da/d07/classllvm_1_1ExtractElementConstantExpr" ],
    [ "InsertElementConstantExpr", "d2/d66/classllvm_1_1InsertElementConstantExpr.html", "d2/d66/classllvm_1_1InsertElementConstantExpr" ],
    [ "ShuffleVectorConstantExpr", "dc/db4/classllvm_1_1ShuffleVectorConstantExpr.html", "dc/db4/classllvm_1_1ShuffleVectorConstantExpr" ],
    [ "ExtractValueConstantExpr", "d3/d2e/classllvm_1_1ExtractValueConstantExpr.html", "d3/d2e/classllvm_1_1ExtractValueConstantExpr" ],
    [ "InsertValueConstantExpr", "d5/dee/classllvm_1_1InsertValueConstantExpr.html", "d5/dee/classllvm_1_1InsertValueConstantExpr" ],
    [ "GetElementPtrConstantExpr", "d6/da7/classllvm_1_1GetElementPtrConstantExpr.html", "d6/da7/classllvm_1_1GetElementPtrConstantExpr" ],
    [ "CompareConstantExpr", "dd/d0d/classllvm_1_1CompareConstantExpr.html", "dd/d0d/classllvm_1_1CompareConstantExpr" ],
    [ "OperandTraits< UnaryConstantExpr >", "d0/dc6/structllvm_1_1OperandTraits_3_01UnaryConstantExpr_01_4.html", "d0/dc6/structllvm_1_1OperandTraits_3_01UnaryConstantExpr_01_4" ],
    [ "OperandTraits< BinaryConstantExpr >", "d7/d61/structllvm_1_1OperandTraits_3_01BinaryConstantExpr_01_4.html", "d7/d61/structllvm_1_1OperandTraits_3_01BinaryConstantExpr_01_4" ],
    [ "OperandTraits< SelectConstantExpr >", "d2/d93/structllvm_1_1OperandTraits_3_01SelectConstantExpr_01_4.html", "d2/d93/structllvm_1_1OperandTraits_3_01SelectConstantExpr_01_4" ],
    [ "OperandTraits< ExtractElementConstantExpr >", "de/de1/structllvm_1_1OperandTraits_3_01ExtractElementConstantExpr_01_4.html", "de/de1/structllvm_1_1OperandTraits_3_01ExtractElementConstantExpr_01_4" ],
    [ "OperandTraits< InsertElementConstantExpr >", "d1/d93/structllvm_1_1OperandTraits_3_01InsertElementConstantExpr_01_4.html", "d1/d93/structllvm_1_1OperandTraits_3_01InsertElementConstantExpr_01_4" ],
    [ "OperandTraits< ShuffleVectorConstantExpr >", "d3/dbe/structllvm_1_1OperandTraits_3_01ShuffleVectorConstantExpr_01_4.html", "d3/dbe/structllvm_1_1OperandTraits_3_01ShuffleVectorConstantExpr_01_4" ],
    [ "OperandTraits< ExtractValueConstantExpr >", "db/d36/structllvm_1_1OperandTraits_3_01ExtractValueConstantExpr_01_4.html", "db/d36/structllvm_1_1OperandTraits_3_01ExtractValueConstantExpr_01_4" ],
    [ "OperandTraits< InsertValueConstantExpr >", "d4/d1a/structllvm_1_1OperandTraits_3_01InsertValueConstantExpr_01_4.html", "d4/d1a/structllvm_1_1OperandTraits_3_01InsertValueConstantExpr_01_4" ],
    [ "OperandTraits< GetElementPtrConstantExpr >", "df/d45/structllvm_1_1OperandTraits_3_01GetElementPtrConstantExpr_01_4.html", "df/d45/structllvm_1_1OperandTraits_3_01GetElementPtrConstantExpr_01_4" ],
    [ "OperandTraits< CompareConstantExpr >", "d4/d0a/structllvm_1_1OperandTraits_3_01CompareConstantExpr_01_4.html", "d4/d0a/structllvm_1_1OperandTraits_3_01CompareConstantExpr_01_4" ],
    [ "ExprMapKeyType", "d1/dd1/structllvm_1_1ExprMapKeyType.html", "d1/dd1/structllvm_1_1ExprMapKeyType" ],
    [ "InlineAsmKeyType", "dc/d5a/structllvm_1_1InlineAsmKeyType.html", "dc/d5a/structllvm_1_1InlineAsmKeyType" ],
    [ "ConstantTraits< std::vector< T, Alloc > >", "d9/dcf/structllvm_1_1ConstantTraits_3_01std_1_1vector_3_01T_00_01Alloc_01_4_01_4.html", "d9/dcf/structllvm_1_1ConstantTraits_3_01std_1_1vector_3_01T_00_01Alloc_01_4_01_4" ],
    [ "ConstantTraits< Constant * >", "d4/d87/structllvm_1_1ConstantTraits_3_01Constant_01_5_01_4.html", "d4/d87/structllvm_1_1ConstantTraits_3_01Constant_01_5_01_4" ],
    [ "ConstantCreator", "da/d06/structllvm_1_1ConstantCreator.html", "da/d06/structllvm_1_1ConstantCreator" ],
    [ "ConstantArrayCreator", "d3/d78/structllvm_1_1ConstantArrayCreator.html", "d3/d78/structllvm_1_1ConstantArrayCreator" ],
    [ "ConstantKeyData", "da/dc2/structllvm_1_1ConstantKeyData.html", "da/dc2/structllvm_1_1ConstantKeyData" ],
    [ "ConstantCreator< ConstantExpr, Type, ExprMapKeyType >", "d1/dfa/structllvm_1_1ConstantCreator_3_01ConstantExpr_00_01Type_00_01ExprMapKeyType_01_4.html", "d1/dfa/structllvm_1_1ConstantCreator_3_01ConstantExpr_00_01Type_00_01ExprMapKeyType_01_4" ],
    [ "ConstantKeyData< ConstantExpr >", "d0/d92/structllvm_1_1ConstantKeyData_3_01ConstantExpr_01_4.html", "d0/d92/structllvm_1_1ConstantKeyData_3_01ConstantExpr_01_4" ],
    [ "ConstantCreator< InlineAsm, PointerType, InlineAsmKeyType >", "df/d1a/structllvm_1_1ConstantCreator_3_01InlineAsm_00_01PointerType_00_01InlineAsmKeyType_01_4.html", "df/d1a/structllvm_1_1ConstantCreator_3_01InlineAsm_00_01PointerType_00_01InlineAsmKeyType_01_4" ],
    [ "ConstantKeyData< InlineAsm >", "d3/d49/structllvm_1_1ConstantKeyData_3_01InlineAsm_01_4.html", "d3/d49/structllvm_1_1ConstantKeyData_3_01InlineAsm_01_4" ],
    [ "ConstantUniqueMap", "d5/dfe/classllvm_1_1ConstantUniqueMap.html", "d5/dfe/classllvm_1_1ConstantUniqueMap" ],
    [ "ConstantAggrUniqueMap", "da/d2f/classllvm_1_1ConstantAggrUniqueMap.html", "da/d2f/classllvm_1_1ConstantAggrUniqueMap" ],
    [ "MapInfo", "d8/db0/structllvm_1_1ConstantAggrUniqueMap_1_1MapInfo.html", "d8/db0/structllvm_1_1ConstantAggrUniqueMap_1_1MapInfo" ],
    [ "DEBUG_TYPE", "dc/d5b/ConstantsContext_8h.html#ad78e062f62e0d6e453941fb4ca843e4d", null ]
];