var namespacellvm_1_1PatternMatch =
[
    [ "OneUse_match", "d5/d17/structllvm_1_1PatternMatch_1_1OneUse__match.html", "d5/d17/structllvm_1_1PatternMatch_1_1OneUse__match" ],
    [ "class_match", "d7/ddc/structllvm_1_1PatternMatch_1_1class__match.html", "d7/ddc/structllvm_1_1PatternMatch_1_1class__match" ],
    [ "match_combine_or", "de/d3f/structllvm_1_1PatternMatch_1_1match__combine__or.html", "de/d3f/structllvm_1_1PatternMatch_1_1match__combine__or" ],
    [ "match_combine_and", "d1/d23/structllvm_1_1PatternMatch_1_1match__combine__and.html", "d1/d23/structllvm_1_1PatternMatch_1_1match__combine__and" ],
    [ "match_zero", "d0/dcf/structllvm_1_1PatternMatch_1_1match__zero.html", "d0/dcf/structllvm_1_1PatternMatch_1_1match__zero" ],
    [ "match_neg_zero", "d6/d27/structllvm_1_1PatternMatch_1_1match__neg__zero.html", "d6/d27/structllvm_1_1PatternMatch_1_1match__neg__zero" ],
    [ "apint_match", "db/dee/structllvm_1_1PatternMatch_1_1apint__match.html", "db/dee/structllvm_1_1PatternMatch_1_1apint__match" ],
    [ "constantint_match", "d7/dc0/structllvm_1_1PatternMatch_1_1constantint__match.html", "d7/dc0/structllvm_1_1PatternMatch_1_1constantint__match" ],
    [ "cst_pred_ty", "d8/d18/structllvm_1_1PatternMatch_1_1cst__pred__ty.html", "d8/d18/structllvm_1_1PatternMatch_1_1cst__pred__ty" ],
    [ "api_pred_ty", "d5/dc2/structllvm_1_1PatternMatch_1_1api__pred__ty.html", "d5/dc2/structllvm_1_1PatternMatch_1_1api__pred__ty" ],
    [ "is_one", "d9/d3f/structllvm_1_1PatternMatch_1_1is__one.html", "d9/d3f/structllvm_1_1PatternMatch_1_1is__one" ],
    [ "is_all_ones", "d8/da1/structllvm_1_1PatternMatch_1_1is__all__ones.html", "d8/da1/structllvm_1_1PatternMatch_1_1is__all__ones" ],
    [ "is_sign_bit", "df/d5d/structllvm_1_1PatternMatch_1_1is__sign__bit.html", "df/d5d/structllvm_1_1PatternMatch_1_1is__sign__bit" ],
    [ "is_power2", "d7/d7e/structllvm_1_1PatternMatch_1_1is__power2.html", "d7/d7e/structllvm_1_1PatternMatch_1_1is__power2" ],
    [ "bind_ty", "d9/d2f/structllvm_1_1PatternMatch_1_1bind__ty.html", "d9/d2f/structllvm_1_1PatternMatch_1_1bind__ty" ],
    [ "specificval_ty", "d3/dcf/structllvm_1_1PatternMatch_1_1specificval__ty.html", "d3/dcf/structllvm_1_1PatternMatch_1_1specificval__ty" ],
    [ "specific_fpval", "de/d6c/structllvm_1_1PatternMatch_1_1specific__fpval.html", "de/d6c/structllvm_1_1PatternMatch_1_1specific__fpval" ],
    [ "bind_const_intval_ty", "db/d6e/structllvm_1_1PatternMatch_1_1bind__const__intval__ty.html", "db/d6e/structllvm_1_1PatternMatch_1_1bind__const__intval__ty" ],
    [ "BinaryOp_match", "d5/da6/structllvm_1_1PatternMatch_1_1BinaryOp__match.html", "d5/da6/structllvm_1_1PatternMatch_1_1BinaryOp__match" ],
    [ "OverflowingBinaryOp_match", "d0/d89/structllvm_1_1PatternMatch_1_1OverflowingBinaryOp__match.html", "d0/d89/structllvm_1_1PatternMatch_1_1OverflowingBinaryOp__match" ],
    [ "BinOp2_match", "dd/dbb/structllvm_1_1PatternMatch_1_1BinOp2__match.html", "dd/dbb/structllvm_1_1PatternMatch_1_1BinOp2__match" ],
    [ "Exact_match", "d5/d98/structllvm_1_1PatternMatch_1_1Exact__match.html", "d5/d98/structllvm_1_1PatternMatch_1_1Exact__match" ],
    [ "CmpClass_match", "d5/d57/structllvm_1_1PatternMatch_1_1CmpClass__match.html", "d5/d57/structllvm_1_1PatternMatch_1_1CmpClass__match" ],
    [ "SelectClass_match", "d2/db4/structllvm_1_1PatternMatch_1_1SelectClass__match.html", "d2/db4/structllvm_1_1PatternMatch_1_1SelectClass__match" ],
    [ "CastClass_match", "d0/db1/structllvm_1_1PatternMatch_1_1CastClass__match.html", "d0/db1/structllvm_1_1PatternMatch_1_1CastClass__match" ],
    [ "not_match", "dc/dae/structllvm_1_1PatternMatch_1_1not__match.html", "dc/dae/structllvm_1_1PatternMatch_1_1not__match" ],
    [ "neg_match", "d0/dc1/structllvm_1_1PatternMatch_1_1neg__match.html", "d0/dc1/structllvm_1_1PatternMatch_1_1neg__match" ],
    [ "fneg_match", "dd/d5e/structllvm_1_1PatternMatch_1_1fneg__match.html", "dd/d5e/structllvm_1_1PatternMatch_1_1fneg__match" ],
    [ "br_match", "df/d67/structllvm_1_1PatternMatch_1_1br__match.html", "df/d67/structllvm_1_1PatternMatch_1_1br__match" ],
    [ "brc_match", "de/dd8/structllvm_1_1PatternMatch_1_1brc__match.html", "de/dd8/structllvm_1_1PatternMatch_1_1brc__match" ],
    [ "MaxMin_match", "de/de2/structllvm_1_1PatternMatch_1_1MaxMin__match.html", "de/de2/structllvm_1_1PatternMatch_1_1MaxMin__match" ],
    [ "smax_pred_ty", "d1/db4/structllvm_1_1PatternMatch_1_1smax__pred__ty.html", "d1/db4/structllvm_1_1PatternMatch_1_1smax__pred__ty" ],
    [ "smin_pred_ty", "d8/d97/structllvm_1_1PatternMatch_1_1smin__pred__ty.html", "d8/d97/structllvm_1_1PatternMatch_1_1smin__pred__ty" ],
    [ "umax_pred_ty", "d4/d92/structllvm_1_1PatternMatch_1_1umax__pred__ty.html", "d4/d92/structllvm_1_1PatternMatch_1_1umax__pred__ty" ],
    [ "umin_pred_ty", "d1/d91/structllvm_1_1PatternMatch_1_1umin__pred__ty.html", "d1/d91/structllvm_1_1PatternMatch_1_1umin__pred__ty" ],
    [ "ofmax_pred_ty", "d6/d90/structllvm_1_1PatternMatch_1_1ofmax__pred__ty.html", "d6/d90/structllvm_1_1PatternMatch_1_1ofmax__pred__ty" ],
    [ "ofmin_pred_ty", "dd/d81/structllvm_1_1PatternMatch_1_1ofmin__pred__ty.html", "dd/d81/structllvm_1_1PatternMatch_1_1ofmin__pred__ty" ],
    [ "ufmax_pred_ty", "dc/dc3/structllvm_1_1PatternMatch_1_1ufmax__pred__ty.html", "dc/dc3/structllvm_1_1PatternMatch_1_1ufmax__pred__ty" ],
    [ "ufmin_pred_ty", "d8/d40/structllvm_1_1PatternMatch_1_1ufmin__pred__ty.html", "d8/d40/structllvm_1_1PatternMatch_1_1ufmin__pred__ty" ],
    [ "Argument_match", "d0/dcd/structllvm_1_1PatternMatch_1_1Argument__match.html", "d0/dcd/structllvm_1_1PatternMatch_1_1Argument__match" ],
    [ "IntrinsicID_match", "dc/d25/structllvm_1_1PatternMatch_1_1IntrinsicID__match.html", "dc/d25/structllvm_1_1PatternMatch_1_1IntrinsicID__match" ],
    [ "m_Intrinsic_Ty", "d2/d8d/structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty.html", null ],
    [ "m_Intrinsic_Ty< T0 >", "d9/d4c/structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty_3_01T0_01_4.html", "d9/d4c/structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty_3_01T0_01_4" ],
    [ "m_Intrinsic_Ty< T0, T1 >", "da/d87/structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty_3_01T0_00_01T1_01_4.html", "da/d87/structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty_3_01T0_00_01T1_01_4" ],
    [ "m_Intrinsic_Ty< T0, T1, T2 >", "d5/d14/structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty_3_01T0_00_01T1_00_01T2_01_4.html", "d5/d14/structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty_3_01T0_00_01T1_00_01T2_01_4" ],
    [ "m_Intrinsic_Ty< T0, T1, T2, T3 >", "dd/d2a/structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty_3_01T0_00_01T1_00_01T2_00_01T3_01_4.html", "dd/d2a/structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty_3_01T0_00_01T1_00_01T2_00_01T3_01_4" ]
];